import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { createAppDatabase } from '../database/database';
import { RunConfigurationRepository } from '../run/run-configuration.repository';
import { RunConfigurationService } from '../run/run-configuration.service';
import { prepareRunProposal } from '../run/run-execution-proposal';
import type { SecretStore } from '../security/secret-store';
import { WorkspaceRepository } from '../workspace/workspace.repository';
import { WorkspaceService } from '../workspace/workspace.service';
import { DebugSessionRepository } from './debug-session.repository';
import { adapterTypeForProject, DebugProposalService } from './debug-proposal.service';

class EmptySecretStore implements SecretStore {
  public async set(): Promise<void> {}
  public async get(): Promise<string | null> {
    return null;
  }
  public async has(): Promise<boolean> {
    return false;
  }
  public async delete(): Promise<boolean> {
    return false;
  }
}

describe('adapterTypeForProject', () => {
  it.each([
    ['node', 'pwa-node'],
    ['typescript', 'pwa-node'],
    ['electron', 'electron-js-debug'],
    ['python', 'debugpy'],
    ['c', 'lldb-dap'],
    ['cpp', 'lldb-dap'],
    ['rust', 'lldb-dap'],
    ['go', 'go-delve'],
    ['dotnet', 'coreclr'],
    ['java-maven', 'java'],
    ['java-gradle', 'java'],
    ['spring-boot', 'java'],
  ])('maps %s projects to %s', (projectType, expected) => {
    expect(adapterTypeForProject(projectType)).toBe(expected);
  });

  it('rejects project types without a registered runtime adapter', () => {
    expect(() => adapterTypeForProject('ruby')).toThrow('尚未提供');
  });

  it.each(['react', 'vue', 'nextjs'])(
    'routes a %s development-server configuration with a port to browser js-debug',
    (projectType) => {
      expect(adapterTypeForProject(projectType, 5173)).toBe('browser-js-debug');
    },
  );
});

describe('remote debug proposal', () => {
  it('creates a high-risk immutable attach snapshot while rejecting ordinary Run', async () => {
    const rootPath = await mkdtemp(join(tmpdir(), 'open-code-desk-debug-proposal-'));
    const database = createAppDatabase(join(rootPath, 'application.sqlite'));
    try {
      const workspaceRepository = new WorkspaceRepository(database);
      const workspace = workspaceRepository.upsert(rootPath);
      const workspaces = new WorkspaceService(workspaceRepository, {
        async pickDirectory() {
          return null;
        },
      });
      await workspaces.openRecent(workspace.id);
      const configurations = new RunConfigurationRepository(database);
      const configuration = await new RunConfigurationService(
        configurations,
        new EmptySecretStore(),
      ).save({
        workspaceId: workspace.id,
        name: 'Remote Node Inspector',
        type: 'node',
        executable: 'node',
        args: [],
        runtimeArgs: [],
        workingDirectory: '',
        environmentVariables: [],
        debugAttach: {
          adapter: 'pwa-node',
          environment: 'remote',
          host: 'debug.internal.example',
          port: 9229,
          remoteRoot: '/srv/app',
        },
        console: 'runOutput',
        autoGenerated: false,
      });

      await expect(
        prepareRunProposal({
          workspaceId: workspace.id,
          configurationId: configuration.id,
          configurations,
          workspaces,
        }),
      ).rejects.toMatchObject({ code: 'RUN_DEBUG_ONLY_CONFIGURATION' });

      const proposal = await new DebugProposalService({
        configurations,
        sessions: new DebugSessionRepository(database),
        workspaces,
        emit() {},
      }).propose({
        workspaceId: workspace.id,
        configurationId: configuration.id,
      });
      expect(proposal).toMatchObject({
        adapterType: 'pwa-node',
        status: 'pending_approval',
        riskLevel: 'high',
        command: { debugAttach: configuration.debugAttach },
      });
      expect(proposal.riskReasons.join(' ')).toContain('debug.internal.example:9229');
      expect(proposal.approvalDigest).toMatch(/^[a-f0-9]{64}$/u);
    } finally {
      database.close();
      await rm(rootPath, { recursive: true, force: true });
    }
  });

  it('includes the exact Electron renderer endpoint in a medium-risk immutable snapshot', async () => {
    const rootPath = await mkdtemp(join(tmpdir(), 'open-code-desk-electron-proposal-'));
    const database = createAppDatabase(join(rootPath, 'application.sqlite'));
    try {
      const workspaceRepository = new WorkspaceRepository(database);
      const workspace = workspaceRepository.upsert(rootPath);
      const workspaces = new WorkspaceService(workspaceRepository, {
        async pickDirectory() {
          return null;
        },
      });
      await workspaces.openRecent(workspace.id);
      const configurations = new RunConfigurationRepository(database);
      const configuration = await new RunConfigurationService(
        configurations,
        new EmptySecretStore(),
      ).save({
        workspaceId: workspace.id,
        name: 'Electron',
        type: 'electron',
        executable: join(rootPath, 'node_modules', 'electron', 'dist', 'electron.exe'),
        args: ['.'],
        runtimeArgs: [],
        workingDirectory: '',
        environmentVariables: [],
        port: 9222,
        console: 'runOutput',
        autoGenerated: false,
      });

      const proposal = await new DebugProposalService({
        configurations,
        sessions: new DebugSessionRepository(database),
        workspaces,
        emit() {},
      }).propose({
        workspaceId: workspace.id,
        configurationId: configuration.id,
      });

      expect(proposal).toMatchObject({
        adapterType: 'electron-js-debug',
        status: 'pending_approval',
        riskLevel: 'medium',
        command: { projectType: 'electron', port: 9222 },
      });
      expect(proposal.riskReasons.join(' ')).toContain('127.0.0.1:9222');
    } finally {
      database.close();
      await rm(rootPath, { recursive: true, force: true });
    }
  });
});
