export type ProjectType =
  | 'node'
  | 'typescript'
  | 'react'
  | 'vue'
  | 'nextjs'
  | 'electron'
  | 'java-maven'
  | 'java-gradle'
  | 'spring-boot'
  | 'python'
  | 'c'
  | 'cpp'
  | 'dotnet'
  | 'go'
  | 'rust'
  | 'script'
  | 'custom';

export type RunConsole = 'integratedTerminal' | 'runOutput';

export type DebugAttachEnvironment = 'remote' | 'container';

/**
 * Connects the bundled Node.js DAP adapter to an already running inspector.
 * Container targets use a user-created port forward; OpenCode Desk never
 * invokes Docker or a remote shell implicitly.
 */
export interface DebugAttachConfiguration {
  readonly adapter: 'pwa-node';
  readonly environment: DebugAttachEnvironment;
  readonly host: string;
  readonly port: number;
  readonly remoteRoot?: string;
}

export type ProjectTaskType =
  'build' | 'clean' | 'test' | 'start' | 'package' | 'deploy' | 'lint' | 'typecheck' | 'custom';

/** A safe renderer-facing environment entry. Sensitive values are never returned. */
export interface RunEnvironmentVariable {
  readonly name: string;
  readonly value?: string;
  readonly sensitive: boolean;
  readonly configured: boolean;
}

export interface RunConfigurationDraft {
  readonly workspaceId: string;
  readonly name: string;
  readonly type: ProjectType;
  readonly executable: string;
  readonly args: ReadonlyArray<string>;
  readonly runtimeArgs: ReadonlyArray<string>;
  /** Workspace-relative working directory. An empty string denotes the workspace root. */
  readonly workingDirectory: string;
  readonly environmentVariables: ReadonlyArray<RunEnvironmentVariable>;
  readonly environmentFile?: string;
  readonly preLaunchTaskId?: string;
  readonly postRunTaskId?: string;
  /** Debug-only attach target. A configuration carrying this value is not runnable. */
  readonly debugAttach?: DebugAttachConfiguration;
  /** TCP port advertised by this service or reserved for its approved debug endpoint. */
  readonly port?: number;
  readonly console: RunConsole;
  readonly autoGenerated: boolean;
}

export interface RunConfiguration extends RunConfigurationDraft {
  readonly id: string;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface CompoundRunConfiguration {
  readonly id: string;
  readonly workspaceId: string;
  readonly name: string;
  readonly configurationIds: ReadonlyArray<string>;
  readonly stopAllOnSingleFailure: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface CompoundRunSession {
  readonly id: string;
  readonly workspaceId: string;
  readonly compoundConfigurationId: string;
  readonly compoundConfigurationName: string;
  readonly executionIds: ReadonlyArray<string>;
  readonly stopAllOnSingleFailure: boolean;
  readonly createdAt: string;
}

export interface CompoundRunProposal {
  readonly session: CompoundRunSession;
  readonly executions: ReadonlyArray<RunExecution>;
}

/** Immutable task command embedded in a parent run/debug approval. */
export interface ProjectTaskCommandSnapshot {
  readonly taskId: string;
  readonly taskUpdatedAt: string;
  readonly taskName: string;
  readonly taskType: ProjectTaskType;
  readonly executable: string;
  readonly args: ReadonlyArray<string>;
  readonly workingDirectory: string;
  readonly environmentVariables: ReadonlyArray<RunEnvironmentVariable>;
  readonly timeoutMs: number;
  readonly riskLevel: RunRiskLevel;
  readonly riskReasons: ReadonlyArray<string>;
}

export interface ProjectTaskPlanSnapshot {
  readonly rootTaskId: string;
  readonly plan: ReadonlyArray<ProjectTaskCommandSnapshot>;
  readonly riskLevel: RunRiskLevel;
  readonly riskReasons: ReadonlyArray<string>;
}

export interface ProjectDetectionEvidence {
  readonly path: string;
  readonly reason: string;
}

export type RuntimeCandidateKind = 'python';
export type RuntimeCandidateSource = 'workspace-venv' | 'active-environment' | 'path' | 'fallback';

/**
 * A runtime discovered without executing project code. The executable is kept
 * explicit so a saved run configuration remains deterministic after restart.
 */
export interface RuntimeCandidate {
  readonly kind: RuntimeCandidateKind;
  readonly executable: string;
  readonly label: string;
  readonly source: RuntimeCandidateSource;
  readonly available: boolean;
  readonly recommended: boolean;
  readonly version?: string;
  readonly reason: string;
}

export interface ProjectDetection {
  readonly workspaceId: string;
  readonly detectedTypes: ReadonlyArray<ProjectType>;
  readonly primaryType: ProjectType;
  readonly evidence: ReadonlyArray<ProjectDetectionEvidence>;
  readonly runtimeCandidates: ReadonlyArray<RuntimeCandidate>;
  readonly suggestedConfigurations: ReadonlyArray<RunConfigurationDraft>;
}

export type RunStatus =
  | 'pending_approval'
  | 'starting'
  | 'running'
  | 'stopping'
  | 'stopped'
  | 'completed'
  | 'failed'
  | 'rejected';

export type RunRiskLevel = 'low' | 'medium' | 'high' | 'blocked';
export type RunApprovalDecision = 'approve' | 'reject';
export type RunOutputStream = 'stdout' | 'stderr';

/**
 * The immutable, renderer-safe command that was reviewed for this execution.
 * Sensitive environment values are deliberately represented only by their
 * safe RunEnvironmentVariable projection.
 */
export interface RunCommandSnapshot {
  readonly configurationId: string;
  readonly configurationUpdatedAt: string;
  readonly configurationName: string;
  readonly projectType: ProjectType;
  readonly executable: string;
  readonly runtimeArgs: ReadonlyArray<string>;
  readonly args: ReadonlyArray<string>;
  /** Workspace-relative working directory. An empty string denotes the workspace root. */
  readonly workingDirectory: string;
  readonly environmentVariables: ReadonlyArray<RunEnvironmentVariable>;
  readonly environmentFile?: string;
  /** SHA-256 of the environment file reviewed at proposal time; never contains its values. */
  readonly environmentFileDigest?: string;
  readonly preLaunchTaskPlan?: ProjectTaskPlanSnapshot;
  readonly postRunTaskPlan?: ProjectTaskPlanSnapshot;
  readonly debugAttach?: DebugAttachConfiguration;
  readonly port?: number;
  readonly console: RunConsole;
}

export interface RunPortInspection {
  readonly port: number;
  readonly available: boolean;
  readonly processId?: number;
  readonly processName?: string;
  /** Present when the listener belongs to a run supervised by this app. */
  readonly managedExecutionId?: string;
}

export interface RunExecutionError {
  readonly code: string;
  readonly message: string;
  readonly retryable: boolean;
}

export interface RunExecution {
  readonly id: string;
  readonly workspaceId: string;
  readonly configurationId: string;
  readonly restartOfExecutionId?: string;
  readonly command: RunCommandSnapshot;
  readonly status: RunStatus;
  readonly riskLevel: RunRiskLevel;
  readonly riskReasons: ReadonlyArray<string>;
  /** SHA-256 digest of the complete approval snapshot. */
  readonly approvalDigest: string;
  readonly approvalDecision?: RunApprovalDecision;
  readonly processId?: number;
  readonly outputTail: string;
  readonly outputBytes: number;
  readonly outputTruncated: boolean;
  readonly exitCode?: number;
  readonly terminationSignal?: string;
  readonly error?: RunExecutionError;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly approvalDecidedAt?: string;
  readonly startedAt?: string;
  readonly completedAt?: string;
}

export interface RunOutputEvent {
  readonly type: 'output';
  readonly executionId: string;
  readonly workspaceId: string;
  readonly stream: RunOutputStream;
  readonly sequence: number;
  readonly data: string;
  readonly occurredAt: string;
}

export interface RunStatusEvent {
  readonly type: 'status';
  readonly execution: RunExecution;
  readonly previousStatus?: RunStatus;
  readonly occurredAt: string;
}

export type RunEvent = RunOutputEvent | RunStatusEvent;
