export type ProjectType =
  | 'node'
  | 'typescript'
  | 'react'
  | 'vue'
  | 'nextjs'
  | 'java-maven'
  | 'java-gradle'
  | 'spring-boot'
  | 'python'
  | 'c'
  | 'cpp'
  | 'dotnet'
  | 'go'
  | 'rust'
  | 'script'
  | 'custom';

export type RunConsole = 'integratedTerminal' | 'runOutput';

/** A safe renderer-facing environment entry. Sensitive values are never returned. */
export interface RunEnvironmentVariable {
  readonly name: string;
  readonly value?: string;
  readonly sensitive: boolean;
  readonly configured: boolean;
}

export interface RunConfigurationDraft {
  readonly workspaceId: string;
  readonly name: string;
  readonly type: ProjectType;
  readonly executable: string;
  readonly args: ReadonlyArray<string>;
  readonly runtimeArgs: ReadonlyArray<string>;
  /** Workspace-relative working directory. An empty string denotes the workspace root. */
  readonly workingDirectory: string;
  readonly environmentVariables: ReadonlyArray<RunEnvironmentVariable>;
  readonly environmentFile?: string;
  readonly preLaunchTaskId?: string;
  readonly postRunTaskId?: string;
  readonly console: RunConsole;
  readonly autoGenerated: boolean;
}

export interface RunConfiguration extends RunConfigurationDraft {
  readonly id: string;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface ProjectDetectionEvidence {
  readonly path: string;
  readonly reason: string;
}

export interface ProjectDetection {
  readonly workspaceId: string;
  readonly detectedTypes: ReadonlyArray<ProjectType>;
  readonly primaryType: ProjectType;
  readonly evidence: ReadonlyArray<ProjectDetectionEvidence>;
  readonly suggestedConfigurations: ReadonlyArray<RunConfigurationDraft>;
}
