import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import type {
  DebugAdapterCapabilities,
  DebugBreakpointKind,
  DebugBreakpointStatus,
  DebugDataBreakpointAccessType,
  DebugExceptionPauseMode,
  DebugPauseLocation,
  DebugSessionError,
  DebugSessionStatus,
  DebugAttachConfiguration,
  ProjectTaskCommandSnapshot,
  ProjectTaskType,
  ProjectType,
  RunApprovalDecision,
  RunCommandSnapshot,
  RunConsole,
  RunExecutionError,
  RunRiskLevel,
  RunStatus,
} from '@open-code-desk/domain';

import { workspaces } from './workspace-schema';

export interface StoredRunEnvironmentVariable {
  readonly name: string;
  readonly value?: string;
  readonly sensitive: boolean;
  readonly configured: boolean;
  readonly secretRef?: string;
}

export const runConfigurations = sqliteTable(
  'run_configurations',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    type: text('type').$type<ProjectType>().notNull(),
    executable: text('executable').notNull(),
    args: text('args', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    runtimeArgs: text('runtime_args', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    workingDirectory: text('working_directory').notNull(),
    environmentVariables: text('environment_variables', { mode: 'json' })
      .$type<ReadonlyArray<StoredRunEnvironmentVariable>>()
      .notNull(),
    environmentFile: text('environment_file'),
    preLaunchTaskId: text('pre_launch_task_id'),
    postRunTaskId: text('post_run_task_id'),
    debugAttach: text('debug_attach', { mode: 'json' }).$type<DebugAttachConfiguration>(),
    port: integer('port'),
    console: text('console').$type<RunConsole>().notNull(),
    autoGenerated: integer('auto_generated', { mode: 'boolean' }).notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('run_configurations_workspace_name_idx').on(table.workspaceId, table.name),
    index('run_configurations_workspace_updated_idx').on(table.workspaceId, table.updatedAt),
  ],
);

export const workspaceRunSettings = sqliteTable('workspace_run_settings', {
  workspaceId: text('workspace_id')
    .primaryKey()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  defaultConfigurationId: text('default_configuration_id').references(() => runConfigurations.id, {
    onDelete: 'set null',
  }),
  updatedAt: text('updated_at').notNull(),
});

export const compoundRunConfigurations = sqliteTable(
  'compound_run_configurations',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    configurationIds: text('configuration_ids', { mode: 'json' })
      .$type<ReadonlyArray<string>>()
      .notNull(),
    stopAllOnSingleFailure: integer('stop_all_on_single_failure', { mode: 'boolean' }).notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('compound_run_configurations_workspace_name_idx').on(table.workspaceId, table.name),
    index('compound_run_configurations_workspace_updated_idx').on(
      table.workspaceId,
      table.updatedAt,
    ),
  ],
);

export const runExecutions = sqliteTable(
  'run_executions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** Kept as a snapshot key so deleting a configuration does not erase its execution history. */
    configurationId: text('configuration_id').notNull(),
    restartOfExecutionId: text('restart_of_execution_id'),
    commandSnapshot: text('command_snapshot', { mode: 'json' })
      .$type<RunCommandSnapshot>()
      .notNull(),
    status: text('status').$type<RunStatus>().notNull(),
    riskLevel: text('risk_level').$type<RunRiskLevel>().notNull(),
    riskReasons: text('risk_reasons', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    approvalDigest: text('approval_digest').notNull(),
    approvalDecision: text('approval_decision').$type<RunApprovalDecision>(),
    processId: integer('process_id'),
    outputTail: text('output_tail').notNull(),
    outputBytes: integer('output_bytes').notNull(),
    outputTruncated: integer('output_truncated', { mode: 'boolean' }).notNull(),
    exitCode: integer('exit_code'),
    terminationSignal: text('termination_signal'),
    error: text('error', { mode: 'json' }).$type<RunExecutionError>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    approvalDecidedAt: text('approval_decided_at'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('run_executions_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('run_executions_configuration_created_idx').on(table.configurationId, table.createdAt),
  ],
);

export const projectTasks = sqliteTable(
  'project_tasks',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    type: text('type').$type<ProjectTaskType>().notNull(),
    executable: text('executable').notNull(),
    args: text('args', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    workingDirectory: text('working_directory').notNull(),
    environmentVariables: text('environment_variables', { mode: 'json' })
      .$type<ReadonlyArray<StoredRunEnvironmentVariable>>()
      .notNull(),
    dependsOn: text('depends_on', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    timeoutMs: integer('timeout_ms').notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('project_tasks_workspace_name_idx').on(table.workspaceId, table.name),
    index('project_tasks_workspace_updated_idx').on(table.workspaceId, table.updatedAt),
  ],
);

export const projectTaskExecutions = sqliteTable(
  'project_task_executions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    rootTaskId: text('root_task_id').notNull(),
    restartOfExecutionId: text('restart_of_execution_id'),
    planSnapshot: text('plan_snapshot', { mode: 'json' })
      .$type<ReadonlyArray<ProjectTaskCommandSnapshot>>()
      .notNull(),
    status: text('status').$type<RunStatus>().notNull(),
    riskLevel: text('risk_level').$type<RunRiskLevel>().notNull(),
    riskReasons: text('risk_reasons', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    approvalDigest: text('approval_digest').notNull(),
    approvalDecision: text('approval_decision').$type<RunApprovalDecision>(),
    currentTaskId: text('current_task_id'),
    currentTaskIndex: integer('current_task_index'),
    processId: integer('process_id'),
    outputTail: text('output_tail').notNull(),
    outputBytes: integer('output_bytes').notNull(),
    outputTruncated: integer('output_truncated', { mode: 'boolean' }).notNull(),
    exitCode: integer('exit_code'),
    terminationSignal: text('termination_signal'),
    error: text('error', { mode: 'json' }).$type<RunExecutionError>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    approvalDecidedAt: text('approval_decided_at'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('project_task_executions_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('project_task_executions_root_created_idx').on(table.rootTaskId, table.createdAt),
  ],
);

export const debugSessions = sqliteTable(
  'debug_sessions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    configurationId: text('configuration_id').notNull(),
    adapterType: text('adapter_type').notNull(),
    commandSnapshot: text('command_snapshot', { mode: 'json' })
      .$type<RunCommandSnapshot>()
      .notNull(),
    status: text('status').$type<DebugSessionStatus>().notNull(),
    riskLevel: text('risk_level').$type<RunRiskLevel>().notNull(),
    riskReasons: text('risk_reasons', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    approvalDigest: text('approval_digest').notNull(),
    approvalDecision: text('approval_decision').$type<RunApprovalDecision>(),
    adapterProcessId: integer('adapter_process_id'),
    capabilities: text('capabilities', { mode: 'json' }).$type<DebugAdapterCapabilities>(),
    pause: text('pause', { mode: 'json' }).$type<DebugPauseLocation>(),
    outputTail: text('output_tail').notNull(),
    outputBytes: integer('output_bytes').notNull(),
    error: text('error', { mode: 'json' }).$type<DebugSessionError>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    approvalDecidedAt: text('approval_decided_at'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('debug_sessions_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('debug_sessions_configuration_created_idx').on(table.configurationId, table.createdAt),
  ],
);

export const debugBreakpoints = sqliteTable(
  'debug_breakpoints',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    relativePath: text('relative_path').notNull(),
    line: integer('line').notNull(),
    column: integer('column').notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).notNull(),
    kind: text('kind').$type<DebugBreakpointKind>().notNull(),
    functionName: text('function_name'),
    dataId: text('data_id'),
    dataAccessType: text('data_access_type').$type<DebugDataBreakpointAccessType>(),
    condition: text('condition'),
    hitCondition: text('hit_condition'),
    logMessage: text('log_message'),
    status: text('status').$type<DebugBreakpointStatus>().notNull(),
    adapterBreakpointId: integer('adapter_breakpoint_id'),
    message: text('message'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('debug_breakpoints_location_idx').on(
      table.workspaceId,
      table.relativePath,
      table.line,
      table.column,
    ),
    index('debug_breakpoints_workspace_path_idx').on(table.workspaceId, table.relativePath),
  ],
);

export const debugSettings = sqliteTable('debug_settings', {
  workspaceId: text('workspace_id')
    .primaryKey()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  exceptionPauseMode: text('exception_pause_mode').$type<DebugExceptionPauseMode>().notNull(),
  exceptionBreakTypes: text('exception_break_types').notNull(),
  exceptionIgnoreTypes: text('exception_ignore_types').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const debugWatches = sqliteTable(
  'debug_watches',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    expression: text('expression').notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('debug_watches_workspace_expression_idx').on(table.workspaceId, table.expression),
    index('debug_watches_workspace_updated_idx').on(table.workspaceId, table.updatedAt),
  ],
);
