import { blob, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import type { AgentTaskCheckpoint } from '@open-code-desk/domain';
import type {
  DebugAdapterCapabilities,
  DebugBreakpointStatus,
  DebugPauseLocation,
  DebugSessionError,
  DebugSessionStatus,
  ProjectType,
  RunApprovalDecision,
  RunCommandSnapshot,
  RunConsole,
  RunExecutionError,
  RunRiskLevel,
  RunStatus,
} from '@open-code-desk/domain';

export interface StoredRunEnvironmentVariable {
  readonly name: string;
  readonly value?: string;
  readonly sensitive: boolean;
  readonly configured: boolean;
  readonly secretRef?: string;
}

export const workspaces = sqliteTable(
  'workspaces',
  {
    id: text('id').primaryKey(),
    canonicalPath: text('canonical_path').notNull().unique(),
    displayName: text('display_name').notNull(),
    lastOpenedAt: text('last_opened_at').notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('workspaces_last_opened_at_idx').on(table.lastOpenedAt)],
);

export const runConfigurations = sqliteTable(
  'run_configurations',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    type: text('type').$type<ProjectType>().notNull(),
    executable: text('executable').notNull(),
    args: text('args', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    runtimeArgs: text('runtime_args', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    workingDirectory: text('working_directory').notNull(),
    environmentVariables: text('environment_variables', { mode: 'json' })
      .$type<ReadonlyArray<StoredRunEnvironmentVariable>>()
      .notNull(),
    environmentFile: text('environment_file'),
    preLaunchTaskId: text('pre_launch_task_id'),
    postRunTaskId: text('post_run_task_id'),
    console: text('console').$type<RunConsole>().notNull(),
    autoGenerated: integer('auto_generated', { mode: 'boolean' }).notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('run_configurations_workspace_name_idx').on(table.workspaceId, table.name),
    index('run_configurations_workspace_updated_idx').on(table.workspaceId, table.updatedAt),
  ],
);

export const workspaceRunSettings = sqliteTable('workspace_run_settings', {
  workspaceId: text('workspace_id')
    .primaryKey()
    .references(() => workspaces.id, { onDelete: 'cascade' }),
  defaultConfigurationId: text('default_configuration_id').references(() => runConfigurations.id, {
    onDelete: 'set null',
  }),
  updatedAt: text('updated_at').notNull(),
});

export const runExecutions = sqliteTable(
  'run_executions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** Kept as a snapshot key so deleting a configuration does not erase its execution history. */
    configurationId: text('configuration_id').notNull(),
    restartOfExecutionId: text('restart_of_execution_id'),
    commandSnapshot: text('command_snapshot', { mode: 'json' })
      .$type<RunCommandSnapshot>()
      .notNull(),
    status: text('status').$type<RunStatus>().notNull(),
    riskLevel: text('risk_level').$type<RunRiskLevel>().notNull(),
    riskReasons: text('risk_reasons', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    approvalDigest: text('approval_digest').notNull(),
    approvalDecision: text('approval_decision').$type<RunApprovalDecision>(),
    processId: integer('process_id'),
    outputTail: text('output_tail').notNull(),
    outputBytes: integer('output_bytes').notNull(),
    outputTruncated: integer('output_truncated', { mode: 'boolean' }).notNull(),
    exitCode: integer('exit_code'),
    terminationSignal: text('termination_signal'),
    error: text('error', { mode: 'json' }).$type<RunExecutionError>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    approvalDecidedAt: text('approval_decided_at'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('run_executions_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('run_executions_configuration_created_idx').on(table.configurationId, table.createdAt),
  ],
);

export const debugSessions = sqliteTable(
  'debug_sessions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    configurationId: text('configuration_id').notNull(),
    adapterType: text('adapter_type').notNull(),
    commandSnapshot: text('command_snapshot', { mode: 'json' })
      .$type<RunCommandSnapshot>()
      .notNull(),
    status: text('status').$type<DebugSessionStatus>().notNull(),
    riskLevel: text('risk_level').$type<RunRiskLevel>().notNull(),
    riskReasons: text('risk_reasons', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    approvalDigest: text('approval_digest').notNull(),
    approvalDecision: text('approval_decision').$type<RunApprovalDecision>(),
    adapterProcessId: integer('adapter_process_id'),
    capabilities: text('capabilities', { mode: 'json' }).$type<DebugAdapterCapabilities>(),
    pause: text('pause', { mode: 'json' }).$type<DebugPauseLocation>(),
    outputTail: text('output_tail').notNull(),
    outputBytes: integer('output_bytes').notNull(),
    error: text('error', { mode: 'json' }).$type<DebugSessionError>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    approvalDecidedAt: text('approval_decided_at'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('debug_sessions_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('debug_sessions_configuration_created_idx').on(table.configurationId, table.createdAt),
  ],
);

export const debugBreakpoints = sqliteTable(
  'debug_breakpoints',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    relativePath: text('relative_path').notNull(),
    line: integer('line').notNull(),
    column: integer('column').notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).notNull(),
    status: text('status').$type<DebugBreakpointStatus>().notNull(),
    adapterBreakpointId: integer('adapter_breakpoint_id'),
    message: text('message'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('debug_breakpoints_location_idx').on(
      table.workspaceId,
      table.relativePath,
      table.line,
      table.column,
    ),
    index('debug_breakpoints_workspace_path_idx').on(table.workspaceId, table.relativePath),
  ],
);

export const debugWatches = sqliteTable(
  'debug_watches',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    expression: text('expression').notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('debug_watches_workspace_expression_idx').on(table.workspaceId, table.expression),
    index('debug_watches_workspace_updated_idx').on(table.workspaceId, table.updatedAt),
  ],
);

export const providerConfigs = sqliteTable(
  'provider_configs',
  {
    id: text('id').primaryKey(),
    kind: text('kind').notNull(),
    displayName: text('display_name').notNull(),
    baseUrl: text('base_url').notNull(),
    defaultModel: text('default_model').notNull(),
    fastModel: text('fast_model'),
    reasoningModel: text('reasoning_model'),
    contextWindow: integer('context_window').notNull(),
    toolCalling: integer('tool_calling', { mode: 'boolean' }).notNull(),
    vision: integer('vision', { mode: 'boolean' }).notNull(),
    streaming: integer('streaming', { mode: 'boolean' }).notNull(),
    customHeaders: text('custom_headers', { mode: 'json' })
      .$type<Readonly<Record<string, string>>>()
      .notNull(),
    sensitiveHeaderNames: text('sensitive_header_names', { mode: 'json' })
      .$type<ReadonlyArray<string>>()
      .notNull(),
    hasApiKey: integer('has_api_key', { mode: 'boolean' }).notNull(),
    secretRef: text('secret_ref'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    index('provider_configs_kind_idx').on(table.kind),
    index('provider_configs_updated_at_idx').on(table.updatedAt),
  ],
);

export const modelConfigs = sqliteTable(
  'model_configs',
  {
    id: text('id').primaryKey(),
    providerConfigId: text('provider_config_id')
      .notNull()
      .references(() => providerConfigs.id, { onDelete: 'cascade' }),
    modelId: text('model_id').notNull(),
    displayName: text('display_name').notNull(),
    ownedBy: text('owned_by'),
    contextWindow: integer('context_window'),
    maxOutputTokens: integer('max_output_tokens'),
    streaming: integer('streaming', { mode: 'boolean' }),
    toolCalling: integer('tool_calling', { mode: 'boolean' }),
    vision: integer('vision', { mode: 'boolean' }),
    reasoning: integer('reasoning', { mode: 'boolean' }),
    structuredOutput: integer('structured_output', { mode: 'boolean' }),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    uniqueIndex('model_configs_provider_model_idx').on(table.providerConfigId, table.modelId),
    index('model_configs_provider_updated_idx').on(table.providerConfigId, table.updatedAt),
  ],
);

export const secureSecrets = sqliteTable('secure_secrets', {
  ref: text('ref').primaryKey(),
  encryptedValue: blob('encrypted_value', { mode: 'buffer' }).notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const conversations = sqliteTable(
  'conversations',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    providerConfigId: text('provider_config_id').references(() => providerConfigs.id, {
      onDelete: 'set null',
    }),
    modelId: text('model_id'),
    status: text('status').notNull(),
    deletedAt: text('deleted_at'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    index('conversations_workspace_updated_idx').on(table.workspaceId, table.updatedAt),
    index('conversations_deleted_at_idx').on(table.deletedAt),
  ],
);

export const messages = sqliteTable(
  'messages',
  {
    id: text('id').primaryKey(),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    role: text('role').notNull(),
    content: text('content').notNull(),
    reasoning: text('reasoning').notNull(),
    toolCallId: text('tool_call_id'),
    toolCalls: text('tool_calls', { mode: 'json' })
      .$type<
        ReadonlyArray<{ readonly id: string; readonly name: string; readonly arguments: string }>
      >()
      .notNull(),
    sequence: integer('sequence').notNull(),
    modelId: text('model_id'),
    status: text('status').notNull(),
    error: text('error', { mode: 'json' }).$type<Readonly<Record<string, unknown>>>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('messages_conversation_sequence_idx').on(table.conversationId, table.sequence)],
);

export const agentTasks = sqliteTable(
  'agent_tasks',
  {
    id: text('id').primaryKey(),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    requestId: text('request_id').notNull().unique(),
    status: text('status').notNull(),
    attempt: integer('attempt').notNull(),
    checkpoint: text('checkpoint', { mode: 'json' }).$type<AgentTaskCheckpoint>(),
    error: text('error', { mode: 'json' }).$type<Readonly<Record<string, unknown>>>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('agent_tasks_conversation_updated_idx').on(table.conversationId, table.updatedAt),
    index('agent_tasks_status_idx').on(table.status),
  ],
);

export const toolCalls = sqliteTable(
  'tool_calls',
  {
    id: text('id').primaryKey(),
    taskId: text('task_id')
      .notNull()
      .references(() => agentTasks.id, { onDelete: 'cascade' }),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    toolName: text('tool_name').notNull(),
    permissionLevel: text('permission_level').notNull(),
    input: text('input', { mode: 'json' }).$type<unknown>().notNull(),
    status: text('status').notNull(),
    output: text('output', { mode: 'json' }).$type<unknown>(),
    error: text('error', { mode: 'json' }).$type<Readonly<Record<string, unknown>>>(),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    index('tool_calls_task_created_idx').on(table.taskId, table.createdAt),
    index('tool_calls_conversation_created_idx').on(table.conversationId, table.createdAt),
  ],
);

export const contextItems = sqliteTable(
  'context_items',
  {
    id: text('id').primaryKey(),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    title: text('title').notNull(),
    content: text('content').notNull(),
    tokenEstimate: integer('token_estimate').notNull(),
    priority: integer('priority').notNull(),
    sourceKey: text('source_key'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    index('context_items_conversation_priority_idx').on(
      table.conversationId,
      table.priority,
      table.createdAt,
    ),
    uniqueIndex('context_items_conversation_source_idx').on(table.conversationId, table.sourceKey),
  ],
);

export const fileChangeSets = sqliteTable(
  'file_change_sets',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    taskId: text('task_id')
      .notNull()
      .references(() => agentTasks.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    status: text('status').notNull(),
    applyDigest: text('apply_digest'),
    error: text('error'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    appliedAt: text('applied_at'),
    rolledBackAt: text('rolled_back_at'),
  },
  (table) => [
    index('file_change_sets_conversation_updated_idx').on(table.conversationId, table.updatedAt),
    index('file_change_sets_task_idx').on(table.taskId),
    index('file_change_sets_status_idx').on(table.status),
  ],
);

export const fileChanges = sqliteTable(
  'file_changes',
  {
    id: text('id').primaryKey(),
    changeSetId: text('change_set_id')
      .notNull()
      .references(() => fileChangeSets.id, { onDelete: 'cascade' }),
    sequence: integer('sequence').notNull(),
    filePath: text('file_path').notNull(),
    destinationPath: text('destination_path'),
    operation: text('operation').notNull(),
    originalArtifactRef: text('original_artifact_ref'),
    proposedArtifactRef: text('proposed_artifact_ref'),
    snapshotArtifactRef: text('snapshot_artifact_ref'),
    baselineHash: text('baseline_hash'),
    proposedHash: text('proposed_hash'),
    appliedHash: text('applied_hash'),
    diff: text('diff').notNull(),
    reviewDigest: text('review_digest').notNull(),
    status: text('status').notNull(),
    error: text('error'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    appliedAt: text('applied_at'),
    rolledBackAt: text('rolled_back_at'),
  },
  (table) => [
    index('file_changes_set_sequence_idx').on(table.changeSetId, table.sequence),
    index('file_changes_set_status_idx').on(table.changeSetId, table.status),
  ],
);

export const commandExecutions = sqliteTable(
  'command_executions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    conversationId: text('conversation_id')
      .notNull()
      .references(() => conversations.id, { onDelete: 'cascade' }),
    taskId: text('task_id')
      .notNull()
      .references(() => agentTasks.id, { onDelete: 'cascade' }),
    modelToolCallId: text('model_tool_call_id').notNull(),
    toolName: text('tool_name').notNull(),
    executable: text('executable').notNull(),
    args: text('args', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    cwd: text('cwd').notNull(),
    timeoutMs: integer('timeout_ms').notNull(),
    riskLevel: text('risk_level').notNull(),
    riskReasons: text('risk_reasons', { mode: 'json' }).$type<ReadonlyArray<string>>().notNull(),
    approvalDigest: text('approval_digest').notNull(),
    status: text('status').notNull(),
    autoApproved: integer('auto_approved', { mode: 'boolean' }).notNull(),
    outputTail: text('output_tail').notNull(),
    outputBytes: integer('output_bytes').notNull(),
    exitCode: integer('exit_code'),
    terminationSignal: text('termination_signal'),
    error: text('error', { mode: 'json' }).$type<Readonly<Record<string, unknown>>>(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
    approvedAt: text('approved_at'),
    startedAt: text('started_at'),
    completedAt: text('completed_at'),
  },
  (table) => [
    index('command_executions_conversation_created_idx').on(table.conversationId, table.createdAt),
    index('command_executions_task_created_idx').on(table.taskId, table.createdAt),
    index('command_executions_status_idx').on(table.status),
  ],
);

export const permissionRules = sqliteTable(
  'permission_rules',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),
    value: text('value').notNull(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [index('permission_rules_workspace_kind_idx').on(table.workspaceId, table.kind)],
);

export const appSettings = sqliteTable('app_settings', {
  key: text('key').primaryKey(),
  value: text('value', { mode: 'json' }).$type<unknown>().notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const auditEvents = sqliteTable(
  'audit_events',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    conversationId: text('conversation_id').references(() => conversations.id, {
      onDelete: 'set null',
    }),
    taskId: text('task_id').references(() => agentTasks.id, { onDelete: 'set null' }),
    actor: text('actor').notNull(),
    category: text('category').notNull(),
    action: text('action').notNull(),
    outcome: text('outcome').notNull(),
    summary: text('summary').notNull(),
    metadata: text('metadata', { mode: 'json' })
      .$type<Readonly<Record<string, string | number | boolean | null>>>()
      .notNull(),
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    index('audit_events_workspace_created_idx').on(table.workspaceId, table.createdAt),
    index('audit_events_conversation_created_idx').on(table.conversationId, table.createdAt),
    index('audit_events_category_created_idx').on(table.category, table.createdAt),
  ],
);

export const crashReports = sqliteTable(
  'crash_reports',
  {
    id: text('id').primaryKey(),
    processType: text('process_type').notNull(),
    reason: text('reason').notNull(),
    exitCode: integer('exit_code'),
    appVersion: text('app_version').notNull(),
    details: text('details', { mode: 'json' })
      .$type<Readonly<Record<string, string | number | boolean | null>>>()
      .notNull(),
    createdAt: text('created_at').notNull(),
    acknowledgedAt: text('acknowledged_at'),
  },
  (table) => [
    index('crash_reports_created_idx').on(table.createdAt),
    index('crash_reports_acknowledged_idx').on(table.acknowledgedAt, table.createdAt),
  ],
);
