import { z } from 'zod';

import {
  debugAttachConfigurationSchema,
  projectTypeSchema,
  runConsoleSchema,
  runEnvironmentVariableInputSchema,
  runEnvironmentVariableSchema,
} from './run-common';
import { argumentSchema, relativePathSchema, uuidSchema, workspaceIdSchema } from './run-internal';

const runConfigurationFields = {
  workspaceId: workspaceIdSchema,
  name: z.string().trim().min(1).max(200),
  type: projectTypeSchema,
  executable: z.string().trim().min(1).max(2_048),
  args: z.array(argumentSchema).max(500).default([]),
  runtimeArgs: z.array(argumentSchema).max(500).default([]),
  workingDirectory: relativePathSchema.default(''),
  environmentVariables: z.array(runEnvironmentVariableSchema).max(500).default([]),
  environmentFile: relativePathSchema.min(1).optional(),
  preLaunchTaskId: uuidSchema.optional(),
  postRunTaskId: uuidSchema.optional(),
  debugAttach: debugAttachConfigurationSchema.optional(),
  port: z.number().int().min(1).max(65_535).optional(),
  console: runConsoleSchema.default('runOutput'),
  autoGenerated: z.boolean(),
} as const;

export const runConfigurationDraftSchema = z.object(runConfigurationFields).strict();

export const runConfigurationSchema = z
  .object({
    id: uuidSchema,
    ...runConfigurationFields,
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  })
  .strict();

export const runConfigurationListSchema = z
  .object({
    configurations: z.array(runConfigurationSchema).max(500),
    defaultConfigurationId: uuidSchema.nullable(),
  })
  .strict();

export const listRunConfigurationsRequestSchema = z
  .object({ workspaceId: workspaceIdSchema })
  .strict();

export const saveRunConfigurationRequestSchema = z
  .object({
    id: uuidSchema.optional(),
    workspaceId: workspaceIdSchema,
    name: runConfigurationFields.name,
    type: projectTypeSchema,
    executable: runConfigurationFields.executable,
    args: z.array(argumentSchema).max(500).default([]),
    runtimeArgs: z.array(argumentSchema).max(500).default([]),
    workingDirectory: relativePathSchema.default(''),
    environmentVariables: z.array(runEnvironmentVariableInputSchema).max(500).default([]),
    environmentFile: relativePathSchema.min(1).optional(),
    preLaunchTaskId: uuidSchema.optional(),
    postRunTaskId: uuidSchema.optional(),
    debugAttach: debugAttachConfigurationSchema.optional(),
    port: runConfigurationFields.port,
    console: runConsoleSchema.default('runOutput'),
    autoGenerated: z.boolean().default(false),
  })
  .strict()
  .superRefine((configuration, context) => {
    if (
      configuration.debugAttach !== undefined &&
      !['node', 'typescript', 'react', 'vue', 'nextjs'].includes(configuration.type)
    ) {
      context.addIssue({
        code: 'custom',
        message: 'Remote/container attach currently requires a Node.js-compatible project type.',
        path: ['debugAttach'],
      });
    }
  });

export const deleteRunConfigurationRequestSchema = z
  .object({ workspaceId: workspaceIdSchema, configurationId: uuidSchema })
  .strict();

export const deleteRunConfigurationResponseSchema = z.object({ deleted: z.boolean() }).strict();

export const duplicateRunConfigurationRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema,
    name: runConfigurationFields.name.optional(),
  })
  .strict();

export const setDefaultRunConfigurationRequestSchema = z
  .object({ workspaceId: workspaceIdSchema, configurationId: uuidSchema.nullable() })
  .strict();

export const setDefaultRunConfigurationResponseSchema = z
  .object({ defaultConfigurationId: uuidSchema.nullable() })
  .strict();

export type RunConfigurationDraft = z.infer<typeof runConfigurationDraftSchema>;
export type RunConfiguration = z.infer<typeof runConfigurationSchema>;
export type RunConfigurationList = z.infer<typeof runConfigurationListSchema>;
export type ListRunConfigurationsRequest = z.infer<typeof listRunConfigurationsRequestSchema>;
export type SaveRunConfigurationRequest = z.infer<typeof saveRunConfigurationRequestSchema>;
export type DeleteRunConfigurationRequest = z.infer<typeof deleteRunConfigurationRequestSchema>;
export type DuplicateRunConfigurationRequest = z.infer<
  typeof duplicateRunConfigurationRequestSchema
>;
export type SetDefaultRunConfigurationRequest = z.infer<
  typeof setDefaultRunConfigurationRequestSchema
>;
export type SetDefaultRunConfigurationResponse = z.infer<
  typeof setDefaultRunConfigurationResponseSchema
>;
