import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import type { RunStatus } from '@open-code-desk/domain';
import { afterEach, describe, expect, it } from 'vitest';

import { createAppDatabase, type AppDatabase } from '../database/database';
import type { SecretStore } from '../security/secret-store';
import { WorkspaceRepository } from '../workspace/workspace.repository';
import { WorkspaceService } from '../workspace/workspace.service';
import { CompoundRunRepository } from './compound-run.repository';
import { CompoundRunService } from './compound-run.service';
import { RunConfigurationRepository } from './run-configuration.repository';
import { RunConfigurationService } from './run-configuration.service';
import { RunExecutionRepository } from './run-execution.repository';
import { RunExecutionService } from './run-execution.service';
import { RunProcessSupervisor } from './run-process-supervisor';

const temporaryPaths: string[] = [];
const databases: AppDatabase[] = [];
const runServices: RunExecutionService[] = [];
const compoundServices: CompoundRunService[] = [];

class MemorySecretStore implements SecretStore {
  readonly values = new Map<string, string>();
  public async set(ref: string, value: string): Promise<void> {
    this.values.set(ref, value);
  }
  public async get(ref: string): Promise<string | null> {
    return this.values.get(ref) ?? null;
  }
  public async has(ref: string): Promise<boolean> {
    return this.values.has(ref);
  }
  public async delete(ref: string): Promise<boolean> {
    return this.values.delete(ref);
  }
}

afterEach(async () => {
  compoundServices.splice(0).forEach((service) => service.close());
  await Promise.all(runServices.splice(0).map((service) => service.close()));
  databases.splice(0).forEach((database) => database.close());
  await Promise.all(
    temporaryPaths.splice(0).map((path) => rm(path, { recursive: true, force: true })),
  );
});

async function createFixture() {
  const rootPath = await mkdtemp(join(tmpdir(), 'open-code-desk-compound-run-'));
  temporaryPaths.push(rootPath);
  const database = createAppDatabase(join(rootPath, 'application.sqlite'));
  databases.push(database);
  const workspaceRepository = new WorkspaceRepository(database);
  const workspace = workspaceRepository.upsert(rootPath);
  const workspaceService = new WorkspaceService(workspaceRepository, {
    async pickDirectory() {
      return null;
    },
  });
  await workspaceService.openRecent(workspace.id);
  const configurations = new RunConfigurationRepository(database);
  const configurationService = new RunConfigurationService(configurations, new MemorySecretStore());
  const executionRepository = new RunExecutionRepository(database);
  const runService = new RunExecutionService(
    configurations,
    executionRepository,
    workspaceService,
    new MemorySecretStore(),
    new RunProcessSupervisor({ gracefulStopTimeoutMs: 200 }),
  );
  runServices.push(runService);
  const compounds = new CompoundRunRepository(database);
  const compoundService = new CompoundRunService(compounds, configurations, runService);
  compoundServices.push(compoundService);
  return {
    database,
    workspace,
    configurations,
    configurationService,
    executionRepository,
    runService,
    compounds,
    compoundService,
  };
}

function waitForExecutionStatus(
  service: RunExecutionService,
  executionId: string,
  status: RunStatus,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      unsubscribe();
      reject(new Error(`Timed out waiting for ${executionId} to become ${status}.`));
    }, 5_000);
    const unsubscribe = service.subscribe((event) => {
      if (
        event.type === 'status' &&
        event.execution.id === executionId &&
        event.execution.status === status
      ) {
        clearTimeout(timeout);
        unsubscribe();
        resolve();
      }
    });
  });
}

async function saveNodeConfiguration(
  fixture: Awaited<ReturnType<typeof createFixture>>,
  name: string,
  source: string,
) {
  return fixture.configurationService.save({
    workspaceId: fixture.workspace.id,
    name,
    type: 'node',
    executable: process.execPath,
    runtimeArgs: ['-e'],
    args: [source],
    workingDirectory: '',
    environmentVariables: [],
    console: 'runOutput',
    autoGenerated: false,
  });
}

describe('CompoundRunService integration', () => {
  it('persists a validated multi-service configuration', async () => {
    const fixture = await createFixture();
    const frontend = await saveNodeConfiguration(fixture, 'frontend', 'process.exit(0)');
    const backend = await saveNodeConfiguration(fixture, 'backend', 'process.exit(0)');

    expect(() =>
      fixture.compoundService.save({
        workspaceId: fixture.workspace.id,
        name: 'invalid',
        configurationIds: [frontend.id],
        stopAllOnSingleFailure: true,
      }),
    ).toThrow('至少需要两个');
    const saved = fixture.compoundService.save({
      workspaceId: fixture.workspace.id,
      name: 'full stack',
      configurationIds: [frontend.id, backend.id],
      stopAllOnSingleFailure: true,
    });

    expect(fixture.compounds.list(fixture.workspace.id)).toEqual([saved]);
    expect(saved.configurationIds).toEqual([frontend.id, backend.id]);
  });

  it('batch-approves concurrent services and stops peers when one fails', async () => {
    const fixture = await createFixture();
    const longLived = await saveNodeConfiguration(
      fixture,
      'frontend',
      'process.stdout.write("ready"); setInterval(() => undefined, 1000)',
    );
    const failing = await saveNodeConfiguration(
      fixture,
      'backend',
      'setTimeout(() => process.exit(7), 200)',
    );
    const compound = fixture.compoundService.save({
      workspaceId: fixture.workspace.id,
      name: 'full stack',
      configurationIds: [longLived.id, failing.id],
      stopAllOnSingleFailure: true,
    });
    const proposal = await fixture.compoundService.proposeStart({
      workspaceId: fixture.workspace.id,
      compoundConfigurationId: compound.id,
    });
    const longExecution = proposal.executions.find(
      (execution) => execution.configurationId === longLived.id,
    );
    const failingExecution = proposal.executions.find(
      (execution) => execution.configurationId === failing.id,
    );
    if (longExecution === undefined || failingExecution === undefined) {
      throw new Error('Expected both compound executions.');
    }
    const failed = waitForExecutionStatus(fixture.runService, failingExecution.id, 'failed');
    const stopped = waitForExecutionStatus(fixture.runService, longExecution.id, 'stopped');
    await Promise.all(
      proposal.executions.map((execution) =>
        fixture.runService.decideStart({
          executionId: execution.id,
          expectedApprovalDigest: execution.approvalDigest,
          decision: 'approve',
        }),
      ),
    );
    await Promise.all([failed, stopped]);

    expect(fixture.executionRepository.findById(failingExecution.id)?.exitCode).toBe(7);
    expect(fixture.executionRepository.findById(longExecution.id)?.status).toBe('stopped');
  });

  it('stops every child in a running compound session on request', async () => {
    const fixture = await createFixture();
    const first = await saveNodeConfiguration(
      fixture,
      'first',
      'setInterval(() => undefined, 1000)',
    );
    const second = await saveNodeConfiguration(
      fixture,
      'second',
      'process.env.COMPOUND_SECOND; setInterval(() => undefined, 1000)',
    );
    const compound = fixture.compoundService.save({
      workspaceId: fixture.workspace.id,
      name: 'services',
      configurationIds: [first.id, second.id],
      stopAllOnSingleFailure: false,
    });
    const proposal = await fixture.compoundService.proposeStart({
      workspaceId: fixture.workspace.id,
      compoundConfigurationId: compound.id,
    });
    const running = proposal.executions.map((execution) =>
      waitForExecutionStatus(fixture.runService, execution.id, 'running'),
    );
    await Promise.all(
      proposal.executions.map((execution) =>
        fixture.runService.decideStart({
          executionId: execution.id,
          expectedApprovalDigest: execution.approvalDigest,
          decision: 'approve',
        }),
      ),
    );
    await Promise.all(running);
    await fixture.compoundService.stopAll({
      workspaceId: fixture.workspace.id,
      sessionId: proposal.session.id,
    });

    expect(
      proposal.executions.map(
        (execution) => fixture.executionRepository.findById(execution.id)?.status,
      ),
    ).toEqual(['stopped', 'stopped']);
  });
});
