import { extname, resolve } from 'node:path';

import type {
  ProjectDetection,
  ProjectDetectionEvidence,
  ProjectType,
  RuntimeCandidate,
  RunConfigurationDraft,
} from '@open-code-desk/domain';
import type { AppSettings } from '@open-code-desk/ipc-contracts';

import { discoverPythonInterpreters } from './python-interpreter-discovery';
import {
  boundedRootFileNames,
  existingFixedMarkers,
  expectedElectronExecutable,
  PACKAGE_JSON_LIMIT,
  packageManager,
  packageScript,
  parsePackageJson,
  primaryTypePriority,
  readBoundedText,
  safePackageEntry,
  TEXT_MARKER_LIMIT,
  uniqueDrafts,
  objectKeys,
} from './project-detector-support';

export async function detectProject(
  workspaceId: string,
  workspaceRoot: string,
  locale: AppSettings['locale'] = 'zh-CN',
): Promise<ProjectDetection> {
  const rootPath = resolve(workspaceRoot);
  const [
    markers,
    rootFileNames,
    packageContent,
    pomContent,
    gradleContent,
    cmakeContent,
    pyprojectContent,
    requirementsContent,
  ] = await Promise.all([
    existingFixedMarkers(rootPath),
    boundedRootFileNames(rootPath),
    readBoundedText(rootPath, 'package.json', PACKAGE_JSON_LIMIT, true),
    readBoundedText(rootPath, 'pom.xml', TEXT_MARKER_LIMIT, false),
    Promise.all([
      readBoundedText(rootPath, 'build.gradle', TEXT_MARKER_LIMIT, false),
      readBoundedText(rootPath, 'build.gradle.kts', TEXT_MARKER_LIMIT, false),
    ]).then((contents) => contents.filter(Boolean).join('\n')),
    readBoundedText(rootPath, 'CMakeLists.txt', TEXT_MARKER_LIMIT, false),
    readBoundedText(rootPath, 'pyproject.toml', TEXT_MARKER_LIMIT, false),
    readBoundedText(rootPath, 'requirements.txt', TEXT_MARKER_LIMIT, false),
  ]);

  const detected = new Set<ProjectType>();
  const evidence: ProjectDetectionEvidence[] = [];
  let runtimeCandidates: ReadonlyArray<RuntimeCandidate> = [];
  const drafts: RunConfigurationDraft[] = [];
  const addType = (projectType: ProjectType, marker: string) => {
    detected.add(projectType);
    if (!evidence.some((item) => item.path === marker)) {
      evidence.push({
        path: marker,
        reason:
          locale === 'zh-CN'
            ? `检测到 ${projectType} 项目标记。`
            : `Detected ${projectType} project marker.`,
      });
    }
  };
  const addDraft = (
    name: string,
    type: ProjectType,
    executable: string,
    args: ReadonlyArray<string>,
    runtimeArgs: ReadonlyArray<string> = [],
    port?: number,
  ) =>
    drafts.push({
      workspaceId,
      name,
      type,
      executable,
      args,
      runtimeArgs,
      workingDirectory: '',
      environmentVariables: [],
      console: 'runOutput',
      autoGenerated: true,
      ...(port === undefined ? {} : { port }),
    });

  const packageJson = parsePackageJson(packageContent);
  if (markers.has('package.json')) {
    addType('node', 'package.json');
    const dependencies = new Set([
      ...objectKeys(packageJson?.dependencies),
      ...objectKeys(packageJson?.devDependencies),
    ]);
    if (markers.has('tsconfig.json') || dependencies.has('typescript'))
      addType('typescript', 'tsconfig.json');
    if (dependencies.has('react')) addType('react', 'package.json#dependencies');
    if (dependencies.has('vue')) addType('vue', 'package.json#dependencies');
    if (dependencies.has('electron')) {
      addType('electron', 'package.json#dependencies');
      addDraft(
        locale === 'zh-CN' ? 'Electron · 主进程与渲染进程' : 'Electron · Main and renderer',
        'electron',
        expectedElectronExecutable(rootPath),
        ['.'],
        [],
        9_222,
      );
    }
    if (
      dependencies.has('next') ||
      [...markers].some((marker) => marker.startsWith('next.config.'))
    ) {
      addType('nextjs', dependencies.has('next') ? 'package.json#dependencies' : 'next.config.*');
    }

    const manager = packageManager(markers);
    const scripts = objectKeys(packageJson?.scripts);
    for (const script of [...scripts].sort().slice(0, 100)) {
      if (/^[a-z0-9][a-z0-9:_-]{0,99}$/iu.test(script)) {
        addDraft(
          `package.json · ${script}`,
          dependencies.has('next')
            ? 'nextjs'
            : dependencies.has('vue')
              ? 'vue'
              : dependencies.has('react')
                ? 'react'
                : 'node',
          manager,
          ['run', script],
          [],
          suggestedFrontendPort(script, packageScript(packageJson?.scripts, script), dependencies),
        );
      }
    }
    const mainEntry = safePackageEntry(packageJson?.main);
    if (mainEntry !== undefined) {
      addDraft(`Node · ${mainEntry}`, 'node', 'node', [mainEntry]);
    }
  } else if (markers.has('tsconfig.json')) {
    addType('typescript', 'tsconfig.json');
  }

  const fixedNodeEntry = [
    'index.js',
    'index.mjs',
    'index.cjs',
    'server.js',
    'server.mjs',
    'server.cjs',
    'app.js',
    'app.mjs',
    'app.cjs',
  ].find((entry) => markers.has(entry));
  if (fixedNodeEntry !== undefined) {
    addType('node', fixedNodeEntry);
    addDraft(`Node · ${fixedNodeEntry}`, 'node', 'node', [fixedNodeEntry]);
  }

  if (markers.has('pom.xml')) {
    addType('java-maven', 'pom.xml');
    const spring = /spring-boot/iu.test(pomContent ?? '');
    if (spring) addType('spring-boot', 'pom.xml');
    const command = markers.has(process.platform === 'win32' ? 'mvnw.cmd' : 'mvnw')
      ? process.platform === 'win32'
        ? '.\\mvnw.cmd'
        : './mvnw'
      : 'mvn';
    addDraft(
      spring ? 'Spring Boot · Maven' : 'Maven · test',
      spring ? 'spring-boot' : 'java-maven',
      command,
      [spring ? 'spring-boot:run' : 'test'],
    );
  }

  const hasGradle = markers.has('build.gradle') || markers.has('build.gradle.kts');
  if (hasGradle) {
    addType('java-gradle', markers.has('build.gradle.kts') ? 'build.gradle.kts' : 'build.gradle');
    const spring = /org\.springframework\.boot|spring-boot/iu.test(gradleContent);
    if (spring) addType('spring-boot', 'build.gradle*');
    const nativeWrapper = process.platform === 'win32' ? 'gradlew.bat' : 'gradlew';
    const command = markers.has(nativeWrapper)
      ? process.platform === 'win32'
        ? '.\\gradlew.bat'
        : './gradlew'
      : 'gradle';
    addDraft(
      spring ? 'Spring Boot · Gradle' : 'Gradle · test',
      spring ? 'spring-boot' : 'java-gradle',
      command,
      [spring ? 'bootRun' : 'test'],
    );
  }

  const pythonMarker = [
    'manage.py',
    'main.py',
    'app.py',
    'pyproject.toml',
    'requirements.txt',
    'Pipfile',
  ].find((marker) => markers.has(marker));
  if (pythonMarker !== undefined) {
    addType('python', pythonMarker);
    runtimeCandidates = await discoverPythonInterpreters(rootPath, { locale });
    const entry = ['manage.py', 'main.py', 'app.py'].find((marker) => markers.has(marker));
    const pythonMetadata = `${pyprojectContent ?? ''}\n${requirementsContent ?? ''}`;
    const interpreter =
      runtimeCandidates[0]?.executable ?? (process.platform === 'win32' ? 'python' : 'python3');
    if (entry !== undefined) {
      addDraft(
        entry === 'manage.py'
          ? locale === 'zh-CN'
            ? 'Python · Django 开发服务器'
            : 'Python · Django development server'
          : `Python · ${entry}`,
        'python',
        interpreter,
        entry === 'manage.py' ? [entry, 'runserver'] : [entry],
      );
    }
    if (/\bflask\b/iu.test(pythonMetadata) && markers.has('app.py')) {
      addDraft(
        locale === 'zh-CN' ? 'Python · Flask 开发服务器' : 'Python · Flask development server',
        'python',
        interpreter,
        ['--app', 'app.py', 'run'],
        ['-m', 'flask'],
      );
    }
    if (/\bfastapi\b/iu.test(pythonMetadata) && /\buvicorn\b/iu.test(pythonMetadata)) {
      const fastApiEntry = markers.has('main.py')
        ? 'main:app'
        : markers.has('app.py')
          ? 'app:app'
          : undefined;
      if (fastApiEntry !== undefined) {
        addDraft(
          'Python · FastAPI (uvicorn)',
          'python',
          interpreter,
          [fastApiEntry, '--reload'],
          ['-m', 'uvicorn'],
        );
      }
    }
    if (markers.has('pytest.ini') || /\bpytest\b/iu.test(pythonMetadata)) {
      addDraft('Python · pytest', 'python', interpreter, [], ['-m', 'pytest']);
    }
  }

  if (markers.has('main.c') || /(?:LANGUAGES\s+[^\n)]*\bC\b|\.c\b)/iu.test(cmakeContent ?? ''))
    addType('c', markers.has('main.c') ? 'main.c' : 'CMakeLists.txt');
  const cppMarker = ['main.cc', 'main.cpp', 'main.cxx'].find((marker) => markers.has(marker));
  if (cppMarker !== undefined || /(?:\bCXX\b|\.c(?:c|pp|xx)\b)/iu.test(cmakeContent ?? ''))
    addType('cpp', cppMarker ?? 'CMakeLists.txt');
  if (markers.has('CMakeLists.txt')) {
    addDraft('CMake · configure', detected.has('cpp') ? 'cpp' : 'c', 'cmake', [
      '-S',
      '.',
      '-B',
      'build',
    ]);
    addDraft('CMake · build', detected.has('cpp') ? 'cpp' : 'c', 'cmake', ['--build', 'build']);
  } else if (markers.has('Makefile') && (detected.has('c') || detected.has('cpp'))) {
    addDraft('Make · build', detected.has('cpp') ? 'cpp' : 'c', 'make', []);
  }

  const dotnetProject = rootFileNames.find((name) =>
    ['.sln', '.csproj', '.fsproj', '.vbproj'].includes(extname(name).toLocaleLowerCase('en-US')),
  );
  if (
    dotnetProject !== undefined ||
    markers.has('global.json') ||
    markers.has('Directory.Build.props')
  ) {
    addType(
      'dotnet',
      dotnetProject ?? (markers.has('global.json') ? 'global.json' : 'Directory.Build.props'),
    );
    addDraft(
      '.NET · run',
      'dotnet',
      'dotnet',
      dotnetProject !== undefined && extname(dotnetProject).toLocaleLowerCase('en-US') !== '.sln'
        ? ['run', '--project', dotnetProject]
        : ['run'],
    );
  }

  if (markers.has('go.mod')) {
    addType('go', 'go.mod');
    addDraft('Go · run', 'go', 'go', ['run', '.']);
  }
  if (markers.has('Cargo.toml')) {
    addType('rust', 'Cargo.toml');
    addDraft('Cargo · run', 'rust', 'cargo', ['run']);
  }

  const scriptMarker = ['run.sh', 'start.sh', 'run.ps1', 'start.ps1', 'run.cmd', 'start.cmd'].find(
    (marker) => markers.has(marker),
  );
  if (scriptMarker !== undefined) {
    addType('script', scriptMarker);
    if (scriptMarker.endsWith('.sh'))
      addDraft(`Script · ${scriptMarker}`, 'script', 'sh', [scriptMarker]);
    else if (scriptMarker.endsWith('.ps1'))
      addDraft(`Script · ${scriptMarker}`, 'script', 'pwsh', ['-File', scriptMarker]);
    else addDraft(`Script · ${scriptMarker}`, 'script', scriptMarker, []);
  }

  const detectedTypes = primaryTypePriority.filter((type) => detected.has(type));
  const primaryType = detectedTypes[0] ?? 'custom';
  return {
    workspaceId,
    primaryType,
    detectedTypes: detectedTypes.length === 0 ? ['custom'] : detectedTypes,
    evidence:
      detectedTypes.length === 0
        ? [
            {
              path: '',
              reason:
                locale === 'zh-CN'
                  ? '未找到支持的根目录项目标记。'
                  : 'No supported root project marker was found.',
            },
          ]
        : evidence,
    runtimeCandidates,
    suggestedConfigurations: uniqueDrafts(drafts),
  };
}

function suggestedFrontendPort(
  scriptName: string,
  command: string | undefined,
  dependencies: ReadonlySet<string>,
): number | undefined {
  if (command === undefined || !/^(?:dev|serve|start)$/iu.test(scriptName)) return undefined;
  const explicit = command.match(/(?:^|\s)(?:--port|-p)(?:=|\s+)(\d{1,5})(?:\s|$)/u)?.[1];
  if (explicit !== undefined) {
    const port = Number(explicit);
    if (Number.isInteger(port) && port >= 1 && port <= 65_535) return port;
  }
  if (/\bvite\b/u.test(command)) return 5_173;
  if (/\bnext\s+dev\b/u.test(command) || /\breact-scripts\s+start\b/u.test(command)) return 3_000;
  if (/\bvue-cli-service\s+serve\b/u.test(command)) return 8_080;
  if (dependencies.has('next')) return 3_000;
  if (dependencies.has('vite')) return 5_173;
  return undefined;
}
