import { randomUUID } from 'node:crypto';

import type {
  DeleteRunConfigurationRequest,
  RunConfiguration as PublicRunConfiguration,
  RunConfigurationList,
  SaveRunConfigurationRequest,
  SetDefaultRunConfigurationRequest,
  SetDefaultRunConfigurationResponse,
} from '@open-code-desk/ipc-contracts';
import type { RunConfiguration } from '@open-code-desk/domain';

import type { StoredRunEnvironmentVariable } from '../database/schema';
import type { SecretStore } from '../security/secret-store';
import type {
  RunConfigurationRepository,
  StoredRunConfiguration,
} from './run-configuration.repository';

interface PreparedEnvironment {
  readonly variables: ReadonlyArray<StoredRunEnvironmentVariable>;
  readonly createdSecretRefs: ReadonlyArray<string>;
}

export class RunConfigurationServiceError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'RunConfigurationServiceError';
  }
}

function secretRefs(configuration: StoredRunConfiguration | null): ReadonlySet<string> {
  return new Set(
    configuration?.environmentVariables.flatMap((variable) =>
      variable.secretRef === undefined ? [] : [variable.secretRef],
    ) ?? [],
  );
}

function toPublicConfiguration(configuration: RunConfiguration): PublicRunConfiguration {
  return {
    ...configuration,
    args: [...configuration.args],
    runtimeArgs: [...configuration.runtimeArgs],
    environmentVariables: configuration.environmentVariables.map((variable) => ({ ...variable })),
  };
}

export class RunConfigurationService {
  public constructor(
    private readonly repository: RunConfigurationRepository,
    private readonly secretStore: SecretStore,
  ) {}

  public list(workspaceId: string): RunConfigurationList {
    return {
      configurations: this.repository.list(workspaceId).map(toPublicConfiguration),
      defaultConfigurationId: this.repository.getDefaultConfigurationId(workspaceId),
    };
  }

  public async save(input: SaveRunConfigurationRequest): Promise<PublicRunConfiguration> {
    const configurationId = input.id ?? randomUUID();
    const existing = this.repository.findStoredById(configurationId);
    if (existing !== null && existing.workspaceId !== input.workspaceId) {
      throw new RunConfigurationServiceError('运行配置不属于当前工作区。');
    }

    const prepared = await this.prepareEnvironment(configurationId, input, existing);
    let saved: RunConfiguration;
    try {
      saved = this.repository.save({
        id: configurationId,
        workspaceId: input.workspaceId,
        name: input.name,
        type: input.type,
        executable: input.executable,
        args: input.args,
        runtimeArgs: input.runtimeArgs,
        workingDirectory: input.workingDirectory,
        environmentVariables: prepared.variables,
        ...(input.environmentFile === undefined ? {} : { environmentFile: input.environmentFile }),
        ...(input.preLaunchTaskId === undefined ? {} : { preLaunchTaskId: input.preLaunchTaskId }),
        ...(input.postRunTaskId === undefined ? {} : { postRunTaskId: input.postRunTaskId }),
        console: input.console,
        autoGenerated: input.autoGenerated,
      });
    } catch (error) {
      await this.deleteSecrets(prepared.createdSecretRefs);
      throw error;
    }

    const retainedRefs = new Set(
      prepared.variables.flatMap((variable) =>
        variable.secretRef === undefined ? [] : [variable.secretRef],
      ),
    );
    await this.deleteSecrets([...secretRefs(existing)].filter((ref) => !retainedRefs.has(ref)));
    return toPublicConfiguration(saved);
  }

  public async delete(input: DeleteRunConfigurationRequest): Promise<boolean> {
    const existing = this.repository.findStoredById(input.configurationId);
    if (existing === null || existing.workspaceId !== input.workspaceId) {
      return false;
    }
    const deleted = this.repository.delete(input.workspaceId, input.configurationId);
    if (deleted) {
      await this.deleteSecrets([...secretRefs(existing)]);
    }
    return deleted;
  }

  public setDefault(input: SetDefaultRunConfigurationRequest): SetDefaultRunConfigurationResponse {
    return {
      defaultConfigurationId: this.repository.setDefaultConfigurationId(
        input.workspaceId,
        input.configurationId,
      ),
    };
  }

  private async prepareEnvironment(
    configurationId: string,
    input: SaveRunConfigurationRequest,
    existing: StoredRunConfiguration | null,
  ): Promise<PreparedEnvironment> {
    const existingByName = new Map(
      existing?.environmentVariables.map((variable) => [variable.name, variable]) ?? [],
    );
    const names = new Set<string>();
    const variables: StoredRunEnvironmentVariable[] = [];
    const createdSecretRefs: string[] = [];

    try {
      for (const variable of input.environmentVariables) {
        if (names.has(variable.name)) {
          throw new RunConfigurationServiceError(`运行环境变量 ${variable.name} 重复。`);
        }
        names.add(variable.name);

        if (!variable.sensitive) {
          variables.push({
            name: variable.name,
            sensitive: false,
            configured: variable.value !== undefined,
            ...(variable.value === undefined ? {} : { value: variable.value }),
          });
          continue;
        }

        if (variable.value === undefined) {
          const previous = existingByName.get(variable.name);
          const secretRef = previous?.sensitive === true ? previous.secretRef : undefined;
          variables.push({
            name: variable.name,
            sensitive: true,
            configured: secretRef !== undefined,
            ...(secretRef === undefined ? {} : { secretRef }),
          });
          continue;
        }

        const secretRef = `run-config:${configurationId}:env:${randomUUID()}`;
        await this.secretStore.set(secretRef, variable.value);
        createdSecretRefs.push(secretRef);
        variables.push({
          name: variable.name,
          sensitive: true,
          configured: true,
          secretRef,
        });
      }
      return { variables, createdSecretRefs };
    } catch (error) {
      await this.deleteSecrets(createdSecretRefs);
      throw error;
    }
  }

  private async deleteSecrets(refs: ReadonlyArray<string>): Promise<void> {
    await Promise.allSettled(refs.map((ref) => this.secretStore.delete(ref)));
  }
}
