import { access, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import type { RunEvent, RunStatus } from '@open-code-desk/domain';
import { afterEach, describe, expect, it } from 'vitest';

import { createAppDatabase, type AppDatabase } from '../database/database';
import type { SecretStore } from '../security/secret-store';
import { WorkspaceRepository } from '../workspace/workspace.repository';
import { WorkspaceService } from '../workspace/workspace.service';
import { RunConfigurationRepository } from './run-configuration.repository';
import { RunConfigurationService } from './run-configuration.service';
import { RunExecutionRepository } from './run-execution.repository';
import { RunExecutionService } from './run-execution.service';
import { RunProcessSupervisor } from './run-process-supervisor';

const temporaryPaths: string[] = [];
const services: RunExecutionService[] = [];
const databases: AppDatabase[] = [];

class MemorySecretStore implements SecretStore {
  readonly values = new Map<string, string>();

  public async set(ref: string, value: string): Promise<void> {
    this.values.set(ref, value);
  }

  public async get(ref: string): Promise<string | null> {
    return this.values.get(ref) ?? null;
  }

  public async has(ref: string): Promise<boolean> {
    return this.values.has(ref);
  }

  public async delete(ref: string): Promise<boolean> {
    return this.values.delete(ref);
  }
}

afterEach(async () => {
  await Promise.all(services.splice(0).map((service) => service.close()));
  databases.splice(0).forEach((database) => database.close());
  await Promise.all(
    temporaryPaths
      .splice(0)
      .map((temporaryPath) => rm(temporaryPath, { recursive: true, force: true })),
  );
});

async function createFixture() {
  const rootPath = await mkdtemp(join(tmpdir(), 'open-code-desk-run-service-'));
  temporaryPaths.push(rootPath);
  const database = createAppDatabase(join(rootPath, 'application.sqlite'));
  databases.push(database);
  const workspaceRepository = new WorkspaceRepository(database);
  const workspace = workspaceRepository.upsert(rootPath);
  const workspaceService = new WorkspaceService(workspaceRepository, {
    async pickDirectory() {
      return null;
    },
  });
  const secrets = new MemorySecretStore();
  const configurationRepository = new RunConfigurationRepository(database);
  const configurationService = new RunConfigurationService(configurationRepository, secrets);
  const executionRepository = new RunExecutionRepository(database);
  const executionService = new RunExecutionService(
    configurationRepository,
    executionRepository,
    workspaceService,
    secrets,
    new RunProcessSupervisor({ gracefulStopTimeoutMs: 200 }),
  );
  services.push(executionService);
  return {
    rootPath,
    database,
    workspace,
    configurationService,
    executionRepository,
    executionService,
  };
}

function waitForStatus(service: RunExecutionService, status: RunStatus): Promise<RunEvent> {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      unsubscribe();
      reject(new Error(`Timed out waiting for run status ${status}.`));
    }, 5_000);
    const unsubscribe = service.subscribe((event) => {
      if (event.type === 'status' && event.execution.status === status) {
        clearTimeout(timeout);
        unsubscribe();
        resolve(event);
      }
    });
  });
}

describe('RunExecutionService integration', () => {
  it('requires approval, streams redacted output, and persists a safe completed history', async () => {
    const fixture = await createFixture();
    const markerPath = join(fixture.rootPath, 'started.txt');
    const secret = 'stage-b-sensitive-token';
    const source = [
      'const fs = require("node:fs");',
      'fs.writeFileSync("started.txt", "started");',
      'process.stdout.write(process.env.RUN_SECRET);',
    ].join(' ');
    const configuration = await fixture.configurationService.save({
      workspaceId: fixture.workspace.id,
      name: '安全运行测试',
      type: 'node',
      executable: process.execPath,
      runtimeArgs: ['-e'],
      args: [source],
      workingDirectory: '',
      environmentVariables: [{ name: 'RUN_SECRET', value: secret, sensitive: true }],
      console: 'runOutput',
      autoGenerated: false,
    });
    const events: RunEvent[] = [];
    fixture.executionService.subscribe((event) => events.push(event));

    const proposal = await fixture.executionService.proposeStart({
      workspaceId: fixture.workspace.id,
      configurationId: configuration.id,
    });
    await expect(access(markerPath)).rejects.toThrow();
    const completedEvent = waitForStatus(fixture.executionService, 'completed');
    await fixture.executionService.decideStart({
      executionId: proposal.id,
      expectedApprovalDigest: proposal.approvalDigest,
      decision: 'approve',
    });
    await completedEvent;

    const completed = fixture.executionRepository.findById(proposal.id);
    expect(completed).toMatchObject({ status: 'completed', exitCode: 0 });
    expect(completed?.outputTail).toContain('[REDACTED]');
    expect(completed?.outputTail).not.toContain(secret);
    expect(
      events.flatMap((event) => (event.type === 'output' ? [event.data] : [])).join(''),
    ).not.toContain(secret);
    const rawDatabase = fixture.database.client
      .prepare('SELECT command_snapshot, output_tail FROM run_executions WHERE id = ?')
      .get(proposal.id) as {
      readonly command_snapshot: string;
      readonly output_tail: string;
    };
    expect(JSON.stringify(rawDatabase)).not.toContain(secret);
  });

  it('stops a long-lived process and creates a separately approved restart proposal', async () => {
    const fixture = await createFixture();
    const configuration = await fixture.configurationService.save({
      workspaceId: fixture.workspace.id,
      name: '长时服务',
      type: 'node',
      executable: process.execPath,
      runtimeArgs: ['-e'],
      args: ['process.stdout.write("ready"); setInterval(() => undefined, 1000);'],
      workingDirectory: '',
      environmentVariables: [],
      console: 'runOutput',
      autoGenerated: false,
    });
    const proposal = await fixture.executionService.proposeStart({
      workspaceId: fixture.workspace.id,
      configurationId: configuration.id,
    });
    await fixture.executionService.decideStart({
      executionId: proposal.id,
      expectedApprovalDigest: proposal.approvalDigest,
      decision: 'approve',
    });
    const stopped = await fixture.executionService.stop({ executionId: proposal.id });
    expect(stopped.status).toBe('stopped');

    const restarted = await fixture.executionService.restart({ executionId: proposal.id });
    expect(restarted).toMatchObject({
      status: 'pending_approval',
      restartOfExecutionId: proposal.id,
    });
    expect(restarted.approvalDigest).not.toBe(proposal.approvalDigest);
  });

  it('fails safely when an approved environment file changed after review', async () => {
    const fixture = await createFixture();
    const environmentPath = join(fixture.rootPath, '.env.run');
    await writeFile(environmentPath, 'RUN_VALUE=first\n', 'utf8');
    const configuration = await fixture.configurationService.save({
      workspaceId: fixture.workspace.id,
      name: '环境文件校验',
      type: 'node',
      executable: process.execPath,
      runtimeArgs: ['-e'],
      args: ['process.stdout.write(process.env.RUN_VALUE);'],
      workingDirectory: '',
      environmentVariables: [],
      environmentFile: '.env.run',
      console: 'runOutput',
      autoGenerated: false,
    });
    const proposal = await fixture.executionService.proposeStart({
      workspaceId: fixture.workspace.id,
      configurationId: configuration.id,
    });
    await writeFile(environmentPath, 'RUN_VALUE=second\n', 'utf8');

    const failed = await fixture.executionService.decideStart({
      executionId: proposal.id,
      expectedApprovalDigest: proposal.approvalDigest,
      decision: 'approve',
    });
    expect(failed).toMatchObject({
      status: 'failed',
      error: { code: 'RUN_START_FAILED', retryable: true },
    });
    expect(failed.outputTail).toBe('');
  });
});
