import { randomUUID } from 'node:crypto';

import type {
  DeleteRunConfigurationRequest,
  DuplicateRunConfigurationRequest,
  RunConfiguration as PublicRunConfiguration,
  RunConfigurationList,
  SaveRunConfigurationRequest,
  SetDefaultRunConfigurationRequest,
  SetDefaultRunConfigurationResponse,
} from '@open-code-desk/ipc-contracts';
import type { RunConfiguration } from '@open-code-desk/domain';

import type { StoredRunEnvironmentVariable } from '../database/schema';
import type { ProjectTaskRepository } from '../project-tasks/project-task.repository';
import type { SecretStore } from '../security/secret-store';
import type {
  RunConfigurationRepository,
  StoredRunConfiguration,
} from './run-configuration.repository';

const nodeAttachProjectTypes = new Set(['node', 'typescript', 'react', 'vue', 'nextjs']);

interface PreparedEnvironment {
  readonly variables: ReadonlyArray<StoredRunEnvironmentVariable>;
  readonly createdSecretRefs: ReadonlyArray<string>;
}

export class RunConfigurationServiceError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'RunConfigurationServiceError';
  }
}

function secretRefs(configuration: StoredRunConfiguration | null): ReadonlySet<string> {
  return new Set(
    configuration?.environmentVariables.flatMap((variable) =>
      variable.secretRef === undefined ? [] : [variable.secretRef],
    ) ?? [],
  );
}

function toPublicConfiguration(configuration: RunConfiguration): PublicRunConfiguration {
  return {
    ...configuration,
    args: [...configuration.args],
    runtimeArgs: [...configuration.runtimeArgs],
    environmentVariables: configuration.environmentVariables.map((variable) => ({ ...variable })),
  };
}

export class RunConfigurationService {
  public constructor(
    private readonly repository: RunConfigurationRepository,
    private readonly secretStore: SecretStore,
    private readonly projectTasks?: ProjectTaskRepository,
  ) {}

  public list(workspaceId: string): RunConfigurationList {
    return {
      configurations: this.repository.list(workspaceId).map(toPublicConfiguration),
      defaultConfigurationId: this.repository.getDefaultConfigurationId(workspaceId),
    };
  }

  public async save(input: SaveRunConfigurationRequest): Promise<PublicRunConfiguration> {
    const configurationId = input.id ?? randomUUID();
    const existing = this.repository.findStoredById(configurationId);
    if (existing !== null && existing.workspaceId !== input.workspaceId) {
      throw new RunConfigurationServiceError('运行配置不属于当前工作区。');
    }
    this.validateTaskReference(input.workspaceId, input.preLaunchTaskId, '启动前');
    this.validateTaskReference(input.workspaceId, input.postRunTaskId, '启动后');
    this.validateDebugAttach(input);

    const prepared = await this.prepareEnvironment(configurationId, input, existing);
    let saved: RunConfiguration;
    try {
      saved = this.repository.save({
        id: configurationId,
        workspaceId: input.workspaceId,
        name: input.name,
        type: input.type,
        executable: input.executable,
        args: input.args,
        runtimeArgs: input.runtimeArgs,
        workingDirectory: input.workingDirectory,
        environmentVariables: prepared.variables,
        ...(input.environmentFile === undefined ? {} : { environmentFile: input.environmentFile }),
        ...(input.preLaunchTaskId === undefined ? {} : { preLaunchTaskId: input.preLaunchTaskId }),
        ...(input.postRunTaskId === undefined ? {} : { postRunTaskId: input.postRunTaskId }),
        ...(input.debugAttach === undefined
          ? {}
          : {
              debugAttach: {
                adapter: input.debugAttach.adapter,
                environment: input.debugAttach.environment,
                host: input.debugAttach.host,
                port: input.debugAttach.port,
                ...(input.debugAttach.remoteRoot === undefined
                  ? {}
                  : { remoteRoot: input.debugAttach.remoteRoot }),
              },
            }),
        ...(input.port === undefined ? {} : { port: input.port }),
        console: input.console,
        autoGenerated: input.autoGenerated,
      });
    } catch (error) {
      await this.deleteSecrets(prepared.createdSecretRefs);
      throw error;
    }

    const retainedRefs = new Set(
      prepared.variables.flatMap((variable) =>
        variable.secretRef === undefined ? [] : [variable.secretRef],
      ),
    );
    await this.deleteSecrets([...secretRefs(existing)].filter((ref) => !retainedRefs.has(ref)));
    return toPublicConfiguration(saved);
  }

  public async delete(input: DeleteRunConfigurationRequest): Promise<boolean> {
    const existing = this.repository.findStoredById(input.configurationId);
    if (existing === null || existing.workspaceId !== input.workspaceId) {
      return false;
    }
    const deleted = this.repository.delete(input.workspaceId, input.configurationId);
    if (deleted) {
      await this.deleteSecrets([...secretRefs(existing)]);
    }
    return deleted;
  }

  public async duplicate(input: DuplicateRunConfigurationRequest): Promise<PublicRunConfiguration> {
    const source = this.repository.findStoredById(input.configurationId);
    if (source === null || source.workspaceId !== input.workspaceId) {
      throw new RunConfigurationServiceError('找不到当前工作区的运行配置。');
    }
    const configurationId = randomUUID();
    const createdSecretRefs: string[] = [];
    try {
      const environmentVariables: StoredRunEnvironmentVariable[] = [];
      for (const variable of source.environmentVariables) {
        if (!variable.sensitive || !variable.configured) {
          environmentVariables.push({ ...variable });
          continue;
        }
        if (variable.secretRef === undefined) {
          throw new RunConfigurationServiceError(`敏感环境变量 ${variable.name} 缺少凭据引用。`);
        }
        const value = await this.secretStore.get(variable.secretRef);
        if (value === null) {
          throw new RunConfigurationServiceError(`敏感环境变量 ${variable.name} 的凭据不可用。`);
        }
        const secretRef = `run-config:${configurationId}:env:${randomUUID()}`;
        await this.secretStore.set(secretRef, value);
        createdSecretRefs.push(secretRef);
        environmentVariables.push({
          name: variable.name,
          sensitive: true,
          configured: true,
          secretRef,
        });
      }
      const saved = this.repository.save({
        id: configurationId,
        workspaceId: source.workspaceId,
        name: input.name ?? this.nextCopyName(source.workspaceId, source.name),
        type: source.type,
        executable: source.executable,
        args: source.args,
        runtimeArgs: source.runtimeArgs,
        workingDirectory: source.workingDirectory,
        environmentVariables,
        ...(source.environmentFile === undefined
          ? {}
          : { environmentFile: source.environmentFile }),
        ...(source.preLaunchTaskId === undefined
          ? {}
          : { preLaunchTaskId: source.preLaunchTaskId }),
        ...(source.postRunTaskId === undefined ? {} : { postRunTaskId: source.postRunTaskId }),
        ...(source.debugAttach === undefined ? {} : { debugAttach: source.debugAttach }),
        ...(source.port === undefined ? {} : { port: source.port }),
        console: source.console,
        autoGenerated: false,
      });
      return toPublicConfiguration(saved);
    } catch (error) {
      await this.deleteSecrets(createdSecretRefs);
      throw error;
    }
  }

  public setDefault(input: SetDefaultRunConfigurationRequest): SetDefaultRunConfigurationResponse {
    return {
      defaultConfigurationId: this.repository.setDefaultConfigurationId(
        input.workspaceId,
        input.configurationId,
      ),
    };
  }

  private async prepareEnvironment(
    configurationId: string,
    input: SaveRunConfigurationRequest,
    existing: StoredRunConfiguration | null,
  ): Promise<PreparedEnvironment> {
    const existingByName = new Map(
      existing?.environmentVariables.map((variable) => [variable.name, variable]) ?? [],
    );
    const names = new Set<string>();
    const variables: StoredRunEnvironmentVariable[] = [];
    const createdSecretRefs: string[] = [];

    try {
      for (const variable of input.environmentVariables) {
        if (names.has(variable.name)) {
          throw new RunConfigurationServiceError(`运行环境变量 ${variable.name} 重复。`);
        }
        names.add(variable.name);

        if (!variable.sensitive) {
          variables.push({
            name: variable.name,
            sensitive: false,
            configured: variable.value !== undefined,
            ...(variable.value === undefined ? {} : { value: variable.value }),
          });
          continue;
        }

        if (variable.value === undefined) {
          const previous = existingByName.get(variable.name);
          const secretRef = previous?.sensitive === true ? previous.secretRef : undefined;
          variables.push({
            name: variable.name,
            sensitive: true,
            configured: secretRef !== undefined,
            ...(secretRef === undefined ? {} : { secretRef }),
          });
          continue;
        }

        const secretRef = `run-config:${configurationId}:env:${randomUUID()}`;
        await this.secretStore.set(secretRef, variable.value);
        createdSecretRefs.push(secretRef);
        variables.push({
          name: variable.name,
          sensitive: true,
          configured: true,
          secretRef,
        });
      }
      return { variables, createdSecretRefs };
    } catch (error) {
      await this.deleteSecrets(createdSecretRefs);
      throw error;
    }
  }

  private validateTaskReference(
    workspaceId: string,
    taskId: string | undefined,
    label: string,
  ): void {
    if (taskId === undefined || this.projectTasks === undefined) return;
    const task = this.projectTasks.findById(taskId);
    if (task === null || task.workspaceId !== workspaceId) {
      throw new RunConfigurationServiceError(`${label}任务不属于当前工作区或已被删除。`);
    }
  }

  private validateDebugAttach(input: SaveRunConfigurationRequest): void {
    if (input.debugAttach !== undefined && !nodeAttachProjectTypes.has(input.type)) {
      throw new RunConfigurationServiceError('远程或容器附加调试当前仅支持 Node.js 兼容项目类型。');
    }
    if (input.type === 'electron' && input.port === undefined) {
      throw new RunConfigurationServiceError('Electron 配置必须指定渲染进程调试端口。');
    }
  }

  private nextCopyName(workspaceId: string, sourceName: string): string {
    const names = new Set(
      this.repository.list(workspaceId).map((configuration) => configuration.name),
    );
    const suffix = ' 副本';
    const base = `${sourceName.slice(0, 200 - suffix.length)}${suffix}`;
    if (!names.has(base)) return base;
    for (let index = 2; index < 10_000; index += 1) {
      const indexSuffix = ` ${index}`;
      const candidate = `${base.slice(0, 200 - indexSuffix.length)}${indexSuffix}`;
      if (!names.has(candidate)) return candidate;
    }
    throw new RunConfigurationServiceError('无法为复制的运行配置生成唯一名称。');
  }

  private async deleteSecrets(refs: ReadonlyArray<string>): Promise<void> {
    await Promise.allSettled(refs.map((ref) => this.secretStore.delete(ref)));
  }
}
