import { DatabaseSync } from 'node:sqlite';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { createAppDatabase } from '../database/database';
import type { SecretStore } from '../security/secret-store';
import { WorkspaceRepository } from '../workspace/workspace.repository';
import { RunConfigurationRepository } from './run-configuration.repository';
import { RunConfigurationService } from './run-configuration.service';

const temporaryPaths: string[] = [];

class MemorySecretStore implements SecretStore {
  readonly values = new Map<string, string>();

  public async set(ref: string, value: string): Promise<void> {
    this.values.set(ref, value);
  }

  public async get(ref: string): Promise<string | null> {
    return this.values.get(ref) ?? null;
  }

  public async has(ref: string): Promise<boolean> {
    return this.values.has(ref);
  }

  public async delete(ref: string): Promise<boolean> {
    return this.values.delete(ref);
  }
}

afterEach(async () => {
  await Promise.all(
    temporaryPaths
      .splice(0)
      .map((temporaryPath) => rm(temporaryPath, { recursive: true, force: true })),
  );
});

describe('run configuration persistence', () => {
  it('persists configurations and defaults without storing sensitive values in plaintext', async () => {
    const temporaryDirectory = await mkdtemp(join(tmpdir(), 'open-code-desk-run-config-'));
    temporaryPaths.push(temporaryDirectory);
    const databasePath = join(temporaryDirectory, 'application.sqlite');
    const secrets = new MemorySecretStore();

    const firstDatabase = createAppDatabase(databasePath);
    const workspace = new WorkspaceRepository(firstDatabase).upsert(temporaryDirectory);
    const firstService = new RunConfigurationService(
      new RunConfigurationRepository(firstDatabase),
      secrets,
    );
    const saved = await firstService.save({
      workspaceId: workspace.id,
      name: '开发服务器',
      type: 'typescript',
      executable: 'pnpm',
      args: ['dev'],
      runtimeArgs: [],
      workingDirectory: '',
      environmentVariables: [
        { name: 'PUBLIC_FLAG', value: 'visible', sensitive: false },
        { name: 'API_TOKEN', value: 'top-secret-value', sensitive: true },
      ],
      console: 'runOutput',
      autoGenerated: false,
    });
    expect(saved.environmentVariables).toEqual([
      { name: 'PUBLIC_FLAG', value: 'visible', sensitive: false, configured: true },
      { name: 'API_TOKEN', sensitive: true, configured: true },
    ]);
    expect(
      firstService.setDefault({
        workspaceId: workspace.id,
        configurationId: saved.id,
      }),
    ).toEqual({ defaultConfigurationId: saved.id });

    const raw = firstDatabase.client
      .prepare('SELECT environment_variables FROM run_configurations WHERE id = ?')
      .get(saved.id) as { readonly environment_variables: string };
    expect(raw.environment_variables).not.toContain('top-secret-value');
    expect(raw.environment_variables).toContain('secretRef');
    expect([...secrets.values.values()]).toEqual(['top-secret-value']);
    firstDatabase.close();

    const reopenedDatabase = createAppDatabase(databasePath);
    const reopenedService = new RunConfigurationService(
      new RunConfigurationRepository(reopenedDatabase),
      secrets,
    );
    expect(reopenedService.list(workspace.id)).toEqual({
      configurations: [saved],
      defaultConfigurationId: saved.id,
    });

    const updated = await reopenedService.save({
      id: saved.id,
      workspaceId: workspace.id,
      name: saved.name,
      type: saved.type,
      executable: saved.executable,
      args: [...saved.args],
      runtimeArgs: [...saved.runtimeArgs],
      workingDirectory: saved.workingDirectory,
      environmentVariables: [
        { name: 'PUBLIC_FLAG', value: 'visible', sensitive: false },
        { name: 'API_TOKEN', sensitive: true },
      ],
      console: saved.console,
      autoGenerated: saved.autoGenerated,
    });
    expect(updated.environmentVariables[1]).toEqual({
      name: 'API_TOKEN',
      sensitive: true,
      configured: true,
    });
    expect([...secrets.values.values()]).toEqual(['top-secret-value']);
    reopenedDatabase.close();
  });

  it('rotates and removes secret references when configurations change or are deleted', async () => {
    const temporaryDirectory = await mkdtemp(join(tmpdir(), 'open-code-desk-run-secret-'));
    temporaryPaths.push(temporaryDirectory);
    const database = createAppDatabase(join(temporaryDirectory, 'application.sqlite'));
    const workspace = new WorkspaceRepository(database).upsert(temporaryDirectory);
    const secrets = new MemorySecretStore();
    const service = new RunConfigurationService(new RunConfigurationRepository(database), secrets);

    const saved = await service.save({
      workspaceId: workspace.id,
      name: '服务',
      type: 'node',
      executable: 'node',
      args: ['server.js'],
      runtimeArgs: [],
      workingDirectory: '',
      environmentVariables: [{ name: 'TOKEN', value: 'first-secret', sensitive: true }],
      console: 'runOutput',
      autoGenerated: false,
    });
    const firstRef = [...secrets.values.keys()][0];
    expect(firstRef).toBeDefined();

    await service.save({
      id: saved.id,
      workspaceId: workspace.id,
      name: saved.name,
      type: saved.type,
      executable: saved.executable,
      args: [...saved.args],
      runtimeArgs: [...saved.runtimeArgs],
      workingDirectory: saved.workingDirectory,
      environmentVariables: [{ name: 'TOKEN', value: 'second-secret', sensitive: true }],
      console: saved.console,
      autoGenerated: saved.autoGenerated,
    });
    expect(firstRef === undefined ? false : secrets.values.has(firstRef)).toBe(false);
    expect([...secrets.values.values()]).toEqual(['second-secret']);

    service.setDefault({ workspaceId: workspace.id, configurationId: saved.id });
    expect(await service.delete({ workspaceId: workspace.id, configurationId: saved.id })).toBe(
      true,
    );
    expect(secrets.values.size).toBe(0);
    expect(service.list(workspace.id)).toEqual({
      configurations: [],
      defaultConfigurationId: null,
    });
    database.close();
  });

  it('upgrades a version 7 database by appending the run configuration migration', async () => {
    const temporaryDirectory = await mkdtemp(join(tmpdir(), 'open-code-desk-run-migration-'));
    temporaryPaths.push(temporaryDirectory);
    const databasePath = join(temporaryDirectory, 'application.sqlite');
    const legacy = new DatabaseSync(databasePath);
    legacy.exec(`
      PRAGMA foreign_keys = ON;
      CREATE TABLE workspaces (
        id TEXT PRIMARY KEY NOT NULL,
        canonical_path TEXT NOT NULL UNIQUE,
        display_name TEXT NOT NULL,
        last_opened_at TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );
      PRAGMA user_version = 7;
    `);
    legacy.close();

    const migrated = createAppDatabase(databasePath);
    const version = migrated.client.prepare('PRAGMA user_version').get() as {
      readonly user_version: number;
    };
    const tables = migrated.client
      .prepare(
        `SELECT name FROM sqlite_master
         WHERE type = 'table' AND name IN ('run_configurations', 'workspace_run_settings')
         ORDER BY name`,
      )
      .all() as unknown as ReadonlyArray<{ readonly name: string }>;
    migrated.close();

    expect(version.user_version).toBe(9);
    expect(tables.map((table) => table.name)).toEqual([
      'run_configurations',
      'workspace_run_settings',
    ]);
  });
});
