import { and, asc, eq } from 'drizzle-orm';
import type { RunConfiguration, RunEnvironmentVariable } from '@open-code-desk/domain';

import type { AppDatabase } from '../database/database';
import {
  runConfigurations,
  type StoredRunEnvironmentVariable,
  workspaceRunSettings,
} from '../database/schema';

export interface StoredRunConfiguration extends Omit<RunConfiguration, 'environmentVariables'> {
  readonly environmentVariables: ReadonlyArray<StoredRunEnvironmentVariable>;
}

export type SaveStoredRunConfiguration = Omit<StoredRunConfiguration, 'createdAt' | 'updatedAt'>;

type RunConfigurationRow = typeof runConfigurations.$inferSelect;

function assertSafeStoredEnvironment(variables: ReadonlyArray<StoredRunEnvironmentVariable>): void {
  const names = new Set<string>();
  for (const variable of variables) {
    if (names.has(variable.name)) {
      throw new Error(`运行环境变量 ${variable.name} 重复。`);
    }
    names.add(variable.name);

    if (variable.sensitive) {
      if (variable.value !== undefined) {
        throw new Error(`敏感运行环境变量 ${variable.name} 不得保存明文值。`);
      }
      if (variable.configured !== (variable.secretRef !== undefined)) {
        throw new Error(`敏感运行环境变量 ${variable.name} 的凭据引用状态无效。`);
      }
      continue;
    }

    if (variable.secretRef !== undefined) {
      throw new Error(`非敏感运行环境变量 ${variable.name} 不得保存凭据引用。`);
    }
    if (variable.configured !== (variable.value !== undefined)) {
      throw new Error(`非敏感运行环境变量 ${variable.name} 的配置状态无效。`);
    }
  }
}

function toPublicEnvironmentVariable(
  variable: StoredRunEnvironmentVariable,
): RunEnvironmentVariable {
  return {
    name: variable.name,
    sensitive: variable.sensitive,
    configured: variable.configured,
    ...(!variable.sensitive && variable.value !== undefined ? { value: variable.value } : {}),
  };
}

function toStoredConfiguration(row: RunConfigurationRow): StoredRunConfiguration {
  assertSafeStoredEnvironment(row.environmentVariables);
  return {
    id: row.id,
    workspaceId: row.workspaceId,
    name: row.name,
    type: row.type,
    executable: row.executable,
    args: row.args,
    runtimeArgs: row.runtimeArgs,
    workingDirectory: row.workingDirectory,
    environmentVariables: row.environmentVariables,
    ...(row.environmentFile === null ? {} : { environmentFile: row.environmentFile }),
    ...(row.preLaunchTaskId === null ? {} : { preLaunchTaskId: row.preLaunchTaskId }),
    ...(row.postRunTaskId === null ? {} : { postRunTaskId: row.postRunTaskId }),
    console: row.console,
    autoGenerated: row.autoGenerated,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function toPublicConfiguration(configuration: StoredRunConfiguration): RunConfiguration {
  return {
    ...configuration,
    environmentVariables: configuration.environmentVariables.map(toPublicEnvironmentVariable),
  };
}

export class RunConfigurationRepository {
  public constructor(private readonly database: AppDatabase) {}

  public findStoredById(configurationId: string): StoredRunConfiguration | null {
    const row = this.database.orm
      .select()
      .from(runConfigurations)
      .where(eq(runConfigurations.id, configurationId))
      .get();
    return row === undefined ? null : toStoredConfiguration(row);
  }

  public findById(configurationId: string): RunConfiguration | null {
    const configuration = this.findStoredById(configurationId);
    return configuration === null ? null : toPublicConfiguration(configuration);
  }

  public list(workspaceId: string): ReadonlyArray<RunConfiguration> {
    return this.database.orm
      .select()
      .from(runConfigurations)
      .where(eq(runConfigurations.workspaceId, workspaceId))
      .orderBy(asc(runConfigurations.name), asc(runConfigurations.id))
      .all()
      .map(toStoredConfiguration)
      .map(toPublicConfiguration);
  }

  public save(input: SaveStoredRunConfiguration): RunConfiguration {
    assertSafeStoredEnvironment(input.environmentVariables);
    const existing = this.findStoredById(input.id);
    if (existing !== null && existing.workspaceId !== input.workspaceId) {
      throw new Error('运行配置不能移动到其他工作区。');
    }

    const now = new Date().toISOString();
    const row = this.database.orm
      .insert(runConfigurations)
      .values({
        ...input,
        environmentFile: input.environmentFile ?? null,
        preLaunchTaskId: input.preLaunchTaskId ?? null,
        postRunTaskId: input.postRunTaskId ?? null,
        createdAt: existing?.createdAt ?? now,
        updatedAt: now,
      })
      .onConflictDoUpdate({
        target: runConfigurations.id,
        set: {
          name: input.name,
          type: input.type,
          executable: input.executable,
          args: input.args,
          runtimeArgs: input.runtimeArgs,
          workingDirectory: input.workingDirectory,
          environmentVariables: input.environmentVariables,
          environmentFile: input.environmentFile ?? null,
          preLaunchTaskId: input.preLaunchTaskId ?? null,
          postRunTaskId: input.postRunTaskId ?? null,
          console: input.console,
          autoGenerated: input.autoGenerated,
          updatedAt: now,
        },
      })
      .returning()
      .get();
    return toPublicConfiguration(toStoredConfiguration(row));
  }

  public delete(workspaceId: string, configurationId: string): boolean {
    return (
      this.database.orm
        .delete(runConfigurations)
        .where(
          and(
            eq(runConfigurations.id, configurationId),
            eq(runConfigurations.workspaceId, workspaceId),
          ),
        )
        .returning({ id: runConfigurations.id })
        .get() !== undefined
    );
  }

  public getDefaultConfigurationId(workspaceId: string): string | null {
    const row = this.database.orm
      .select({ defaultConfigurationId: workspaceRunSettings.defaultConfigurationId })
      .from(workspaceRunSettings)
      .where(eq(workspaceRunSettings.workspaceId, workspaceId))
      .get();
    return row?.defaultConfigurationId ?? null;
  }

  public setDefaultConfigurationId(
    workspaceId: string,
    configurationId: string | null,
  ): string | null {
    if (configurationId !== null) {
      const configuration = this.findStoredById(configurationId);
      if (configuration === null || configuration.workspaceId !== workspaceId) {
        throw new Error('默认运行配置必须属于当前工作区。');
      }
    }

    const updatedAt = new Date().toISOString();
    this.database.orm
      .insert(workspaceRunSettings)
      .values({ workspaceId, defaultConfigurationId: configurationId, updatedAt })
      .onConflictDoUpdate({
        target: workspaceRunSettings.workspaceId,
        set: { defaultConfigurationId: configurationId, updatedAt },
      })
      .run();
    return configurationId;
  }
}
