import type {
  ProjectType,
  RunConfiguration,
  SaveRunConfigurationRequest,
} from '@open-code-desk/ipc-contracts';
import { Trash2, X } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import {
  blankRunConfigurationDraft,
  draftFromRunConfiguration,
  nonEmptyLines,
  projectTypes,
  runConfigurationInputClassName,
  type ConfigurationDraft,
} from './run-configuration-draft';
import { RunEnvironmentEditor } from './run-environment-editor';
import { useRunStore } from './run.store';

export function RunConfigurationDialog() {
  const open = useRunStore((state) => state.dialogOpen);
  const editingConfigurationId = useRunStore((state) => state.editingConfigurationId);
  const configurations = useRunStore((state) => state.configurations);
  const defaultConfigurationId = useRunStore((state) => state.defaultConfigurationId);
  const workspaceId = useRunStore((state) => state.workspaceId);
  const editing = configurations.find(
    (configuration) => configuration.id === editingConfigurationId,
  );

  if (!open || workspaceId === undefined) {
    return null;
  }

  return (
    <RunConfigurationDialogForm
      key={editing?.id ?? 'new'}
      workspaceId={workspaceId}
      editing={editing}
      defaultConfigurationId={defaultConfigurationId}
    />
  );
}

interface RunConfigurationDialogFormProps {
  readonly workspaceId: string;
  readonly editing: RunConfiguration | undefined;
  readonly defaultConfigurationId: string | null;
}

function RunConfigurationDialogForm({
  workspaceId,
  editing,
  defaultConfigurationId,
}: RunConfigurationDialogFormProps) {
  const loading = useRunStore((state) => state.loading);
  const errorMessage = useRunStore((state) => state.errorMessage);
  const close = useRunStore((state) => state.closeConfigurationDialog);
  const saveConfiguration = useRunStore((state) => state.saveConfiguration);
  const deleteConfiguration = useRunStore((state) => state.deleteConfiguration);
  const setDefaultConfiguration = useRunStore((state) => state.setDefaultConfiguration);
  const [draft, setDraft] = useState<ConfigurationDraft>(() =>
    editing === undefined
      ? blankRunConfigurationDraft()
      : draftFromRunConfiguration(editing, defaultConfigurationId),
  );

  const save = async () => {
    const input: SaveRunConfigurationRequest = {
      ...(editing === undefined ? {} : { id: editing.id }),
      workspaceId,
      name: draft.name,
      type: draft.type,
      executable: draft.executable,
      args: [...nonEmptyLines(draft.args)],
      runtimeArgs: [...nonEmptyLines(draft.runtimeArgs)],
      workingDirectory: draft.workingDirectory,
      environmentVariables: draft.environmentVariables
        .filter((variable) => variable.name.trim() !== '')
        .map((variable) => ({
          name: variable.name,
          ...(variable.value === '' && variable.sensitive && variable.configured
            ? {}
            : { value: variable.value }),
          sensitive: variable.sensitive,
        })),
      ...(draft.environmentFile.trim() === ''
        ? {}
        : { environmentFile: draft.environmentFile.trim() }),
      ...(editing?.preLaunchTaskId === undefined
        ? {}
        : { preLaunchTaskId: editing.preLaunchTaskId }),
      ...(editing?.postRunTaskId === undefined ? {} : { postRunTaskId: editing.postRunTaskId }),
      console: draft.console,
      autoGenerated: editing?.autoGenerated ?? false,
    };

    try {
      const saved = await saveConfiguration(input);
      if (draft.makeDefault) {
        await setDefaultConfiguration(saved.id);
      } else if (defaultConfigurationId === saved.id) {
        await setDefaultConfiguration(null);
      }
      close();
    } catch {
      // The store keeps a user-readable error in the open dialog.
    }
  };

  return (
    <div
      className="fixed inset-0 z-[55] grid place-items-center bg-black/70 p-4 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label="运行配置"
      data-testid="run-configuration-dialog"
    >
      <section className="flex max-h-[94vh] w-[min(780px,96vw)] flex-col overflow-hidden rounded-2xl border border-zinc-700 bg-zinc-900 shadow-2xl">
        <header className="flex h-14 shrink-0 items-center border-b border-zinc-800 px-5">
          <div>
            <h2 className="text-sm font-semibold text-zinc-100">
              {editing === undefined ? '新增运行配置' : `编辑 ${editing.name}`}
            </h2>
            <p className="text-[11px] text-zinc-500">参数每行一个；敏感环境变量不会回显</p>
          </div>
          <button
            type="button"
            className="ml-auto rounded-lg p-2 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-100"
            onClick={close}
            aria-label="关闭运行配置"
          >
            <X className="size-4" aria-hidden="true" />
          </button>
        </header>

        <div className="min-h-0 flex-1 space-y-5 overflow-auto p-5">
          <div className="grid gap-4 sm:grid-cols-2">
            <label className="space-y-1.5 text-xs text-zinc-400">
              <span>名称</span>
              <input
                className={runConfigurationInputClassName}
                value={draft.name}
                onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))}
                required
                data-testid="run-config-name"
              />
            </label>
            <label className="space-y-1.5 text-xs text-zinc-400">
              <span>项目类型</span>
              <select
                className={runConfigurationInputClassName}
                value={draft.type}
                onChange={(event) =>
                  setDraft((value) => ({ ...value, type: event.target.value as ProjectType }))
                }
                data-testid="run-config-type"
              >
                {projectTypes.map((type) => (
                  <option key={type} value={type}>
                    {type}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <label className="block space-y-1.5 text-xs text-zinc-400">
            <span>可执行文件</span>
            <input
              className={runConfigurationInputClassName}
              value={draft.executable}
              onChange={(event) =>
                setDraft((value) => ({ ...value, executable: event.target.value }))
              }
              placeholder="例如 pnpm、node、python"
              required
              data-testid="run-config-executable"
            />
          </label>

          <div className="grid gap-4 sm:grid-cols-2">
            <label className="space-y-1.5 text-xs text-zinc-400">
              <span>运行时参数（每行一个）</span>
              <textarea
                className="min-h-28 w-full rounded-md border border-zinc-700 bg-zinc-950 p-3 font-mono text-xs text-zinc-100 outline-none focus:border-cyan-500"
                value={draft.runtimeArgs}
                onChange={(event) =>
                  setDraft((value) => ({ ...value, runtimeArgs: event.target.value }))
                }
                data-testid="run-config-runtime-args"
              />
            </label>
            <label className="space-y-1.5 text-xs text-zinc-400">
              <span>程序参数（每行一个）</span>
              <textarea
                className="min-h-28 w-full rounded-md border border-zinc-700 bg-zinc-950 p-3 font-mono text-xs text-zinc-100 outline-none focus:border-cyan-500"
                value={draft.args}
                onChange={(event) => setDraft((value) => ({ ...value, args: event.target.value }))}
                data-testid="run-config-args"
              />
            </label>
          </div>

          <label className="block space-y-1.5 text-xs text-zinc-400">
            <span>工作目录（工作区相对路径，留空为根目录）</span>
            <input
              className={runConfigurationInputClassName}
              value={draft.workingDirectory}
              onChange={(event) =>
                setDraft((value) => ({ ...value, workingDirectory: event.target.value }))
              }
              data-testid="run-config-cwd"
            />
          </label>

          <div className="grid gap-4 sm:grid-cols-2">
            <label className="space-y-1.5 text-xs text-zinc-400">
              <span>环境文件（工作区相对路径，可选）</span>
              <input
                className={runConfigurationInputClassName}
                value={draft.environmentFile}
                onChange={(event) =>
                  setDraft((value) => ({ ...value, environmentFile: event.target.value }))
                }
                placeholder="例如 .env.local"
                data-testid="run-config-environment-file"
              />
            </label>
            <label className="space-y-1.5 text-xs text-zinc-400">
              <span>输出位置</span>
              <select
                className={runConfigurationInputClassName}
                value={draft.console}
                onChange={(event) =>
                  setDraft((value) => ({
                    ...value,
                    console: event.target.value as ConfigurationDraft['console'],
                  }))
                }
                data-testid="run-config-console"
              >
                <option value="runOutput">运行输出</option>
                <option value="integratedTerminal">集成终端</option>
              </select>
            </label>
          </div>

          <RunEnvironmentEditor
            variables={draft.environmentVariables}
            onChange={(environmentVariables) =>
              setDraft((value) => ({ ...value, environmentVariables }))
            }
          />

          <label className="flex items-center gap-2 text-xs text-zinc-400">
            <input
              type="checkbox"
              checked={draft.makeDefault}
              onChange={(event) =>
                setDraft((value) => ({ ...value, makeDefault: event.target.checked }))
              }
            />
            设为当前工作区默认运行配置
          </label>

          {errorMessage === undefined ? null : (
            <p
              className="rounded-lg border border-red-900 bg-red-950/50 px-3 py-2 text-xs text-red-300"
              role="alert"
            >
              {errorMessage}
            </p>
          )}
        </div>

        <footer className="flex h-14 shrink-0 items-center gap-2 border-t border-zinc-800 px-5">
          {editing === undefined ? null : (
            <Button
              type="button"
              variant="outline"
              className="text-red-300 hover:text-red-200"
              disabled={loading}
              onClick={() => {
                if (window.confirm(`确定删除“${editing.name}”吗？`)) {
                  void deleteConfiguration(editing.id);
                }
              }}
              data-testid="delete-run-configuration"
            >
              <Trash2 className="size-4" aria-hidden="true" />
              删除
            </Button>
          )}
          <Button type="button" variant="outline" className="ml-auto" onClick={close}>
            取消
          </Button>
          <Button
            type="button"
            disabled={loading || draft.name.trim() === '' || draft.executable.trim() === ''}
            onClick={() => void save()}
            data-testid="save-run-configuration"
          >
            {loading ? '保存中…' : '保存'}
          </Button>
        </footer>
      </section>
    </div>
  );
}
