import type {
  RunConfigurationDraft,
  RunExecution,
  RunOutputStream,
  SaveRunConfigurationRequest,
} from '@open-code-desk/ipc-contracts';

import { rendererErrorMessage } from '../settings/error-i18n';

const maximumOutputTail = 65_536;

export interface RunOutputChunk {
  readonly stream: RunOutputStream;
  readonly sequence: number;
  readonly data: string;
}

export function readableRunError(error: unknown): string {
  return rendererErrorMessage(error, 'runOperationFailed');
}

const statusRank: Readonly<Record<RunExecution['status'], number>> = {
  pending_approval: 0,
  starting: 1,
  running: 2,
  stopping: 3,
  stopped: 4,
  completed: 4,
  failed: 4,
  rejected: 4,
};

export function mergeRunExecution(
  executions: ReadonlyArray<RunExecution>,
  updated: RunExecution,
): ReadonlyArray<RunExecution> {
  const current = executions.find((execution) => execution.id === updated.id);
  if (current === undefined) {
    return [updated, ...executions].sort((left, right) =>
      right.createdAt.localeCompare(left.createdAt),
    );
  }
  const isNewer = updated.updatedAt > current.updatedAt;
  const isEquivalentOrFurther =
    updated.updatedAt === current.updatedAt &&
    (statusRank[updated.status] > statusRank[current.status] ||
      (statusRank[updated.status] === statusRank[current.status] &&
        updated.outputBytes >= current.outputBytes));
  if (!isNewer && !isEquivalentOrFurther) {
    return executions;
  }
  return executions
    .map((execution) => (execution.id === updated.id ? updated : execution))
    .sort((left, right) => right.createdAt.localeCompare(left.createdAt));
}

export function appendRunOutput(execution: RunExecution, chunk: string): RunExecution {
  return {
    ...execution,
    outputTail: `${execution.outputTail}${chunk}`.slice(-maximumOutputTail),
    outputBytes: execution.outputBytes + new TextEncoder().encode(chunk).byteLength,
  };
}

export function isActiveRunStatus(status: RunExecution['status']): boolean {
  return ['pending_approval', 'starting', 'running', 'stopping'].includes(status);
}

export function suggestionToSaveRequest(
  suggestion: RunConfigurationDraft,
): SaveRunConfigurationRequest {
  return {
    workspaceId: suggestion.workspaceId,
    name: suggestion.name,
    type: suggestion.type,
    executable: suggestion.executable,
    args: [...suggestion.args],
    runtimeArgs: [...suggestion.runtimeArgs],
    workingDirectory: suggestion.workingDirectory,
    environmentVariables: suggestion.environmentVariables.map((variable) => ({
      name: variable.name,
      ...(variable.value === undefined ? {} : { value: variable.value }),
      sensitive: variable.sensitive,
    })),
    ...(suggestion.environmentFile === undefined
      ? {}
      : { environmentFile: suggestion.environmentFile }),
    ...(suggestion.preLaunchTaskId === undefined
      ? {}
      : { preLaunchTaskId: suggestion.preLaunchTaskId }),
    ...(suggestion.postRunTaskId === undefined ? {} : { postRunTaskId: suggestion.postRunTaskId }),
    console: suggestion.console,
    autoGenerated: suggestion.autoGenerated,
  };
}
