import { describe, expect, it } from 'vitest';

import { runCommandSnapshotSchema, saveRunConfigurationRequestSchema } from './run';

const base = {
  workspaceId: '00000000-0000-4000-8000-000000000001',
  name: 'Remote Node',
  type: 'node' as const,
  executable: 'node',
  args: [],
  runtimeArgs: [],
  workingDirectory: '',
  environmentVariables: [],
  console: 'runOutput' as const,
  autoGenerated: false,
};

describe('debug attach configuration contracts', () => {
  it('accepts bounded Node.js remote and container targets', () => {
    expect(
      saveRunConfigurationRequestSchema.parse({
        ...base,
        debugAttach: {
          adapter: 'pwa-node',
          environment: 'container',
          host: '127.0.0.1',
          port: 9229,
          remoteRoot: '/workspace/app',
        },
      }).debugAttach,
    ).toEqual({
      adapter: 'pwa-node',
      environment: 'container',
      host: '127.0.0.1',
      port: 9229,
      remoteRoot: '/workspace/app',
    });
  });

  it('rejects unsupported project types, URL-shaped hosts and relative remote roots', () => {
    const target = {
      adapter: 'pwa-node' as const,
      environment: 'remote' as const,
      host: 'https://debug.example.test/path',
      port: 9229,
      remoteRoot: '../outside',
    };
    expect(
      saveRunConfigurationRequestSchema.safeParse({ ...base, type: 'python', debugAttach: target })
        .success,
    ).toBe(false);
    expect(
      saveRunConfigurationRequestSchema.safeParse({ ...base, debugAttach: target }).success,
    ).toBe(false);
  });

  it('preserves the reviewed attach endpoint in the immutable command snapshot', () => {
    const command = runCommandSnapshotSchema.parse({
      configurationId: '00000000-0000-4000-8000-000000000002',
      configurationUpdatedAt: '2026-08-04T00:00:00.000Z',
      configurationName: 'Remote Node',
      projectType: 'node',
      executable: 'node',
      runtimeArgs: [],
      args: [],
      workingDirectory: '',
      environmentVariables: [],
      debugAttach: {
        adapter: 'pwa-node',
        environment: 'remote',
        host: 'debug.example.test',
        port: 9229,
      },
      console: 'runOutput',
    });
    expect(command.debugAttach).toMatchObject({ host: 'debug.example.test', port: 9229 });
  });
});
