import { z } from 'zod';

const uuidSchema = z.string().uuid();
const workspaceIdSchema = uuidSchema;
const relativePathSchema = z.string().max(2_048);
const argumentSchema = z.string().max(32_768);

export const projectTypeSchema = z.enum([
  'node',
  'typescript',
  'react',
  'vue',
  'nextjs',
  'java-maven',
  'java-gradle',
  'spring-boot',
  'python',
  'c',
  'cpp',
  'dotnet',
  'go',
  'rust',
  'script',
  'custom',
]);

export const runConsoleSchema = z.enum(['integratedTerminal', 'runOutput']);

export const runChannels = {
  deleteConfiguration: 'run:delete-configuration',
  detectProject: 'run:detect-project',
  listConfigurations: 'run:list-configurations',
  saveConfiguration: 'run:save-configuration',
  setDefaultConfiguration: 'run:set-default-configuration',
} as const;

const environmentVariableNameSchema = z
  .string()
  .trim()
  .min(1)
  .max(255)
  .regex(/^[^=\u0000]+$/, 'Environment variable names cannot contain equals signs or null bytes.');

export const runEnvironmentVariableInputSchema = z
  .object({
    name: environmentVariableNameSchema,
    value: z.string().max(65_536).optional(),
    sensitive: z.boolean().default(false),
  })
  .strict();

export const runEnvironmentVariableSchema = z
  .object({
    name: environmentVariableNameSchema,
    value: z.string().max(65_536).optional(),
    sensitive: z.boolean(),
    configured: z.boolean(),
  })
  .strict()
  .superRefine((variable, context) => {
    if (variable.sensitive && variable.value !== undefined) {
      context.addIssue({
        code: 'custom',
        message: 'Sensitive environment variable values must not be exposed.',
        path: ['value'],
      });
    }
  });

const runConfigurationFields = {
  workspaceId: workspaceIdSchema,
  name: z.string().trim().min(1).max(200),
  type: projectTypeSchema,
  executable: z.string().trim().min(1).max(2_048),
  args: z.array(argumentSchema).max(500).default([]),
  runtimeArgs: z.array(argumentSchema).max(500).default([]),
  workingDirectory: relativePathSchema.default(''),
  environmentVariables: z.array(runEnvironmentVariableSchema).max(500).default([]),
  environmentFile: relativePathSchema.min(1).optional(),
  preLaunchTaskId: uuidSchema.optional(),
  postRunTaskId: uuidSchema.optional(),
  console: runConsoleSchema.default('runOutput'),
  autoGenerated: z.boolean(),
} as const;

export const runConfigurationDraftSchema = z.object(runConfigurationFields).strict();

export const runConfigurationSchema = z
  .object({
    id: uuidSchema,
    ...runConfigurationFields,
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  })
  .strict();

export const runConfigurationListSchema = z
  .object({
    configurations: z.array(runConfigurationSchema).max(500),
    defaultConfigurationId: uuidSchema.nullable(),
  })
  .strict();

export const projectDetectionEvidenceSchema = z
  .object({
    path: relativePathSchema,
    reason: z.string().min(1).max(2_000),
  })
  .strict();

export const projectDetectionSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    detectedTypes: z.array(projectTypeSchema).min(1).max(20),
    primaryType: projectTypeSchema,
    evidence: z.array(projectDetectionEvidenceSchema).max(100),
    suggestedConfigurations: z.array(runConfigurationDraftSchema).max(100),
  })
  .strict()
  .superRefine((detection, context) => {
    if (!detection.detectedTypes.includes(detection.primaryType)) {
      context.addIssue({
        code: 'custom',
        message: 'The primary project type must be included in detectedTypes.',
        path: ['primaryType'],
      });
    }
    for (const [index, configuration] of detection.suggestedConfigurations.entries()) {
      if (configuration.workspaceId !== detection.workspaceId) {
        context.addIssue({
          code: 'custom',
          message: 'Suggested configurations must belong to the detected workspace.',
          path: ['suggestedConfigurations', index, 'workspaceId'],
        });
      }
    }
  });

export const detectProjectRequestSchema = z.object({ workspaceId: workspaceIdSchema }).strict();
export const listRunConfigurationsRequestSchema = z
  .object({ workspaceId: workspaceIdSchema })
  .strict();

export const saveRunConfigurationRequestSchema = z
  .object({
    id: uuidSchema.optional(),
    workspaceId: workspaceIdSchema,
    name: runConfigurationFields.name,
    type: projectTypeSchema,
    executable: runConfigurationFields.executable,
    args: z.array(argumentSchema).max(500).default([]),
    runtimeArgs: z.array(argumentSchema).max(500).default([]),
    workingDirectory: relativePathSchema.default(''),
    environmentVariables: z.array(runEnvironmentVariableInputSchema).max(500).default([]),
    environmentFile: relativePathSchema.min(1).optional(),
    preLaunchTaskId: uuidSchema.optional(),
    postRunTaskId: uuidSchema.optional(),
    console: runConsoleSchema.default('runOutput'),
    autoGenerated: z.boolean().default(false),
  })
  .strict();

export const deleteRunConfigurationRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema,
  })
  .strict();

export const deleteRunConfigurationResponseSchema = z.object({ deleted: z.boolean() }).strict();

export const setDefaultRunConfigurationRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema.nullable(),
  })
  .strict();

export const setDefaultRunConfigurationResponseSchema = z
  .object({ defaultConfigurationId: uuidSchema.nullable() })
  .strict();

export type ProjectType = z.infer<typeof projectTypeSchema>;
export type RunConsole = z.infer<typeof runConsoleSchema>;
export type RunEnvironmentVariableInput = z.infer<typeof runEnvironmentVariableInputSchema>;
export type RunEnvironmentVariable = z.infer<typeof runEnvironmentVariableSchema>;
export type RunConfigurationDraft = z.infer<typeof runConfigurationDraftSchema>;
export type RunConfiguration = z.infer<typeof runConfigurationSchema>;
export type RunConfigurationList = z.infer<typeof runConfigurationListSchema>;
export type ProjectDetectionEvidence = z.infer<typeof projectDetectionEvidenceSchema>;
export type ProjectDetection = z.infer<typeof projectDetectionSchema>;
export type DetectProjectRequest = z.infer<typeof detectProjectRequestSchema>;
export type ListRunConfigurationsRequest = z.infer<typeof listRunConfigurationsRequestSchema>;
export type SaveRunConfigurationRequest = z.infer<typeof saveRunConfigurationRequestSchema>;
export type DeleteRunConfigurationRequest = z.infer<typeof deleteRunConfigurationRequestSchema>;
export type SetDefaultRunConfigurationRequest = z.infer<
  typeof setDefaultRunConfigurationRequestSchema
>;
export type SetDefaultRunConfigurationResponse = z.infer<
  typeof setDefaultRunConfigurationResponseSchema
>;
