import { z } from 'zod';

const uuidSchema = z.string().uuid();
const workspaceIdSchema = uuidSchema;
const relativePathSchema = z.string().max(2_048);
const argumentSchema = z.string().max(32_768);

export const projectTypeSchema = z.enum([
  'node',
  'typescript',
  'react',
  'vue',
  'nextjs',
  'java-maven',
  'java-gradle',
  'spring-boot',
  'python',
  'c',
  'cpp',
  'dotnet',
  'go',
  'rust',
  'script',
  'custom',
]);

export const runConsoleSchema = z.enum(['integratedTerminal', 'runOutput']);

export const runChannels = {
  decideStart: 'run:decide-start',
  deleteConfiguration: 'run:delete-configuration',
  detectProject: 'run:detect-project',
  event: 'run:event',
  listConfigurations: 'run:list-configurations',
  listHistory: 'run:list-history',
  proposeStart: 'run:propose-start',
  restart: 'run:restart',
  saveConfiguration: 'run:save-configuration',
  setDefaultConfiguration: 'run:set-default-configuration',
  stop: 'run:stop',
} as const;

const environmentVariableNameSchema = z
  .string()
  .trim()
  .min(1)
  .max(255)
  .regex(/^[^=\u0000]+$/, 'Environment variable names cannot contain equals signs or null bytes.');

export const runEnvironmentVariableInputSchema = z
  .object({
    name: environmentVariableNameSchema,
    value: z.string().max(65_536).optional(),
    sensitive: z.boolean().default(false),
  })
  .strict();

export const runEnvironmentVariableSchema = z
  .object({
    name: environmentVariableNameSchema,
    value: z.string().max(65_536).optional(),
    sensitive: z.boolean(),
    configured: z.boolean(),
  })
  .strict()
  .superRefine((variable, context) => {
    if (variable.sensitive && variable.value !== undefined) {
      context.addIssue({
        code: 'custom',
        message: 'Sensitive environment variable values must not be exposed.',
        path: ['value'],
      });
    }
  });

const runConfigurationFields = {
  workspaceId: workspaceIdSchema,
  name: z.string().trim().min(1).max(200),
  type: projectTypeSchema,
  executable: z.string().trim().min(1).max(2_048),
  args: z.array(argumentSchema).max(500).default([]),
  runtimeArgs: z.array(argumentSchema).max(500).default([]),
  workingDirectory: relativePathSchema.default(''),
  environmentVariables: z.array(runEnvironmentVariableSchema).max(500).default([]),
  environmentFile: relativePathSchema.min(1).optional(),
  preLaunchTaskId: uuidSchema.optional(),
  postRunTaskId: uuidSchema.optional(),
  console: runConsoleSchema.default('runOutput'),
  autoGenerated: z.boolean(),
} as const;

export const runConfigurationDraftSchema = z.object(runConfigurationFields).strict();

export const runConfigurationSchema = z
  .object({
    id: uuidSchema,
    ...runConfigurationFields,
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  })
  .strict();

export const runConfigurationListSchema = z
  .object({
    configurations: z.array(runConfigurationSchema).max(500),
    defaultConfigurationId: uuidSchema.nullable(),
  })
  .strict();

export const projectDetectionEvidenceSchema = z
  .object({
    path: relativePathSchema,
    reason: z.string().min(1).max(2_000),
  })
  .strict();

export const projectDetectionSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    detectedTypes: z.array(projectTypeSchema).min(1).max(20),
    primaryType: projectTypeSchema,
    evidence: z.array(projectDetectionEvidenceSchema).max(100),
    suggestedConfigurations: z.array(runConfigurationDraftSchema).max(100),
  })
  .strict()
  .superRefine((detection, context) => {
    if (!detection.detectedTypes.includes(detection.primaryType)) {
      context.addIssue({
        code: 'custom',
        message: 'The primary project type must be included in detectedTypes.',
        path: ['primaryType'],
      });
    }
    for (const [index, configuration] of detection.suggestedConfigurations.entries()) {
      if (configuration.workspaceId !== detection.workspaceId) {
        context.addIssue({
          code: 'custom',
          message: 'Suggested configurations must belong to the detected workspace.',
          path: ['suggestedConfigurations', index, 'workspaceId'],
        });
      }
    }
  });

export const detectProjectRequestSchema = z.object({ workspaceId: workspaceIdSchema }).strict();
export const listRunConfigurationsRequestSchema = z
  .object({ workspaceId: workspaceIdSchema })
  .strict();

export const saveRunConfigurationRequestSchema = z
  .object({
    id: uuidSchema.optional(),
    workspaceId: workspaceIdSchema,
    name: runConfigurationFields.name,
    type: projectTypeSchema,
    executable: runConfigurationFields.executable,
    args: z.array(argumentSchema).max(500).default([]),
    runtimeArgs: z.array(argumentSchema).max(500).default([]),
    workingDirectory: relativePathSchema.default(''),
    environmentVariables: z.array(runEnvironmentVariableInputSchema).max(500).default([]),
    environmentFile: relativePathSchema.min(1).optional(),
    preLaunchTaskId: uuidSchema.optional(),
    postRunTaskId: uuidSchema.optional(),
    console: runConsoleSchema.default('runOutput'),
    autoGenerated: z.boolean().default(false),
  })
  .strict();

export const deleteRunConfigurationRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema,
  })
  .strict();

export const deleteRunConfigurationResponseSchema = z.object({ deleted: z.boolean() }).strict();

export const setDefaultRunConfigurationRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema.nullable(),
  })
  .strict();

export const setDefaultRunConfigurationResponseSchema = z
  .object({ defaultConfigurationId: uuidSchema.nullable() })
  .strict();

export const runStatusSchema = z.enum([
  'pending_approval',
  'starting',
  'running',
  'stopping',
  'stopped',
  'completed',
  'failed',
  'rejected',
]);

export const runRiskLevelSchema = z.enum(['low', 'medium', 'high', 'blocked']);
export const runApprovalDecisionSchema = z.enum(['approve', 'reject']);
export const runOutputStreamSchema = z.enum(['stdout', 'stderr']);

export const runCommandSnapshotSchema = z
  .object({
    configurationId: uuidSchema,
    configurationUpdatedAt: z.string().datetime(),
    configurationName: z.string().trim().min(1).max(200),
    projectType: projectTypeSchema,
    executable: z.string().trim().min(1).max(2_048),
    runtimeArgs: z.array(argumentSchema).max(500),
    args: z.array(argumentSchema).max(500),
    workingDirectory: relativePathSchema,
    environmentVariables: z.array(runEnvironmentVariableSchema).max(500),
    environmentFile: relativePathSchema.min(1).optional(),
    environmentFileDigest: z
      .string()
      .regex(/^[a-f0-9]{64}$/i, 'Expected a SHA-256 digest.')
      .optional(),
    console: runConsoleSchema,
  })
  .strict();

export const runExecutionErrorSchema = z
  .object({
    code: z.string().trim().min(1).max(100),
    message: z.string().trim().min(1).max(4_000),
    retryable: z.boolean(),
  })
  .strict();

const runExecutionFields = {
  id: uuidSchema,
  workspaceId: workspaceIdSchema,
  configurationId: uuidSchema,
  restartOfExecutionId: uuidSchema.optional(),
  command: runCommandSnapshotSchema,
  riskLevel: runRiskLevelSchema,
  riskReasons: z.array(z.string().trim().min(1).max(1_000)).max(20),
  approvalDigest: z.string().regex(/^[a-f0-9]{64}$/i, 'Expected a SHA-256 digest.'),
  approvalDecision: runApprovalDecisionSchema.optional(),
  processId: z.number().int().positive().optional(),
  outputTail: z.string().max(65_536),
  outputBytes: z.number().int().nonnegative(),
  outputTruncated: z.boolean(),
  exitCode: z.number().int().optional(),
  terminationSignal: z.string().trim().min(1).max(100).optional(),
  error: runExecutionErrorSchema.optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  approvalDecidedAt: z.string().datetime().optional(),
  startedAt: z.string().datetime().optional(),
  completedAt: z.string().datetime().optional(),
} as const;

const runExecutionBaseSchema = z.object(runExecutionFields).strict();

export const runExecutionSchema = runExecutionBaseSchema
  .extend({ status: runStatusSchema })
  .superRefine((execution, context) => {
    if (execution.command.configurationId !== execution.configurationId) {
      context.addIssue({
        code: 'custom',
        message: 'The command snapshot must belong to the execution configuration.',
        path: ['command', 'configurationId'],
      });
    }

    if (execution.status === 'pending_approval' && execution.approvalDecision !== undefined) {
      context.addIssue({
        code: 'custom',
        message: 'A pending execution cannot already have an approval decision.',
        path: ['approvalDecision'],
      });
    }

    if (execution.status === 'rejected' && execution.approvalDecision !== 'reject') {
      context.addIssue({
        code: 'custom',
        message: 'A rejected execution must record a reject decision.',
        path: ['approvalDecision'],
      });
    }

    if (
      ['starting', 'running', 'stopping', 'stopped', 'completed', 'failed'].includes(
        execution.status,
      ) &&
      execution.approvalDecision !== 'approve'
    ) {
      context.addIssue({
        code: 'custom',
        message: 'An execution cannot start without an approve decision.',
        path: ['approvalDecision'],
      });
    }
  });

/** Start and restart proposals are incapable of representing an already-started execution. */
export const pendingRunExecutionSchema = runExecutionBaseSchema
  .extend({ status: z.literal('pending_approval') })
  .superRefine((execution, context) => {
    if (execution.command.configurationId !== execution.configurationId) {
      context.addIssue({
        code: 'custom',
        message: 'The command snapshot must belong to the execution configuration.',
        path: ['command', 'configurationId'],
      });
    }
    if (execution.approvalDecision !== undefined) {
      context.addIssue({
        code: 'custom',
        message: 'A pending execution cannot already have an approval decision.',
        path: ['approvalDecision'],
      });
    }
  });

export const runExecutionListSchema = z.array(runExecutionSchema).max(1_000);

export const proposeRunStartRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema,
  })
  .strict();

export const decideRunStartRequestSchema = z
  .object({
    executionId: uuidSchema,
    expectedApprovalDigest: z.string().regex(/^[a-f0-9]{64}$/i, 'Expected a SHA-256 digest.'),
    decision: runApprovalDecisionSchema,
  })
  .strict();

export const stopRunExecutionRequestSchema = z.object({ executionId: uuidSchema }).strict();

export const restartRunExecutionRequestSchema = z.object({ executionId: uuidSchema }).strict();

export const listRunHistoryRequestSchema = z
  .object({
    workspaceId: workspaceIdSchema,
    configurationId: uuidSchema.optional(),
    limit: z.number().int().min(1).max(1_000).default(100),
  })
  .strict();

export const runOutputEventSchema = z
  .object({
    type: z.literal('output'),
    executionId: uuidSchema,
    workspaceId: workspaceIdSchema,
    stream: runOutputStreamSchema,
    sequence: z.number().int().nonnegative(),
    data: z.string().max(65_536),
    occurredAt: z.string().datetime(),
  })
  .strict();

export const runStatusEventSchema = z
  .object({
    type: z.literal('status'),
    execution: runExecutionSchema,
    previousStatus: runStatusSchema.optional(),
    occurredAt: z.string().datetime(),
  })
  .strict();

export const runEventSchema = z.discriminatedUnion('type', [
  runOutputEventSchema,
  runStatusEventSchema,
]);

export type ProjectType = z.infer<typeof projectTypeSchema>;
export type RunConsole = z.infer<typeof runConsoleSchema>;
export type RunEnvironmentVariableInput = z.infer<typeof runEnvironmentVariableInputSchema>;
export type RunEnvironmentVariable = z.infer<typeof runEnvironmentVariableSchema>;
export type RunConfigurationDraft = z.infer<typeof runConfigurationDraftSchema>;
export type RunConfiguration = z.infer<typeof runConfigurationSchema>;
export type RunConfigurationList = z.infer<typeof runConfigurationListSchema>;
export type ProjectDetectionEvidence = z.infer<typeof projectDetectionEvidenceSchema>;
export type ProjectDetection = z.infer<typeof projectDetectionSchema>;
export type DetectProjectRequest = z.infer<typeof detectProjectRequestSchema>;
export type ListRunConfigurationsRequest = z.infer<typeof listRunConfigurationsRequestSchema>;
export type SaveRunConfigurationRequest = z.infer<typeof saveRunConfigurationRequestSchema>;
export type DeleteRunConfigurationRequest = z.infer<typeof deleteRunConfigurationRequestSchema>;
export type SetDefaultRunConfigurationRequest = z.infer<
  typeof setDefaultRunConfigurationRequestSchema
>;
export type SetDefaultRunConfigurationResponse = z.infer<
  typeof setDefaultRunConfigurationResponseSchema
>;
export type RunStatus = z.infer<typeof runStatusSchema>;
export type RunRiskLevel = z.infer<typeof runRiskLevelSchema>;
export type RunApprovalDecision = z.infer<typeof runApprovalDecisionSchema>;
export type RunOutputStream = z.infer<typeof runOutputStreamSchema>;
export type RunCommandSnapshot = z.infer<typeof runCommandSnapshotSchema>;
export type RunExecutionError = z.infer<typeof runExecutionErrorSchema>;
export type RunExecution = z.infer<typeof runExecutionSchema>;
export type PendingRunExecution = z.infer<typeof pendingRunExecutionSchema>;
export type ProposeRunStartRequest = z.infer<typeof proposeRunStartRequestSchema>;
export type DecideRunStartRequest = z.infer<typeof decideRunStartRequestSchema>;
export type StopRunExecutionRequest = z.infer<typeof stopRunExecutionRequestSchema>;
export type RestartRunExecutionRequest = z.infer<typeof restartRunExecutionRequestSchema>;
export type ListRunHistoryRequest = z.infer<typeof listRunHistoryRequestSchema>;
export type RunOutputEvent = z.infer<typeof runOutputEventSchema>;
export type RunStatusEvent = z.infer<typeof runStatusEventSchema>;
export type RunEvent = z.infer<typeof runEventSchema>;
